using Encina.Compliance.AIAct.Attributes;
using Encina.Compliance.AIAct.Model;
using LanguageExt;

namespace Encina.UnitTests.Compliance.AIAct;

/// <summary>
/// Shared test stubs for AI Act compliance tests.
/// </summary>
internal sealed record SampleNoAttributeRequest : ICommand<Unit>;

[HighRiskAI(Category = AISystemCategory.EmploymentWorkersManagement)]
internal sealed record SampleHighRiskRequest : ICommand<Unit>;

[HighRiskAI(Category = AISystemCategory.EmploymentWorkersManagement, SystemId = "cv-screener")]
internal sealed record SampleHighRiskWithIdRequest : ICommand<Unit>;

[RequireHumanOversight(Reason = "Loan decisions require human review")]
internal sealed record SampleOversightRequest : ICommand<Unit>;

[AITransparency("This content was generated by AI.")]
internal sealed record SampleTransparencyRequest : ICommand<Unit>;

[HighRiskAI(Category = AISystemCategory.EmploymentWorkersManagement)]
[RequireHumanOversight(Reason = "Employment decisions must be reviewed")]
[AITransparency("AI-assisted screening result.")]
internal sealed record SampleFullyDecoratedRequest : ICommand<Unit>;
