CREATE TABLE `DataProcessingAgreements` (
    `Id`                              VARCHAR(256)  NOT NULL PRIMARY KEY,
    `ProcessorId`                     VARCHAR(256)  NOT NULL,
    `StatusValue`                     INT           NOT NULL,
    `SignedAtUtc`                     DATETIME(6)   NOT NULL,
    `ExpiresAtUtc`                    DATETIME(6)   NULL,
    `HasSCCs`                         TINYINT(1)    NOT NULL,
    `ProcessingPurposesJson`          JSON          NOT NULL,
    `ProcessOnDocumentedInstructions` TINYINT(1)    NOT NULL,
    `ConfidentialityObligations`      TINYINT(1)    NOT NULL,
    `SecurityMeasures`                TINYINT(1)    NOT NULL,
    `SubProcessorRequirements`        TINYINT(1)    NOT NULL,
    `DataSubjectRightsAssistance`     TINYINT(1)    NOT NULL,
    `ComplianceAssistance`            TINYINT(1)    NOT NULL,
    `DataDeletionOrReturn`            TINYINT(1)    NOT NULL,
    `AuditRights`                     TINYINT(1)    NOT NULL,
    `TenantId`                        VARCHAR(256)  NULL,
    `ModuleId`                        VARCHAR(256)  NULL,
    `CreatedAtUtc`                    DATETIME(6)   NOT NULL,
    `LastUpdatedAtUtc`                DATETIME(6)   NOT NULL,
    INDEX `IX_DataProcessingAgreements_ProcessorId` (`ProcessorId`),
    INDEX `IX_DataProcessingAgreements_StatusValue` (`StatusValue`),
    INDEX `IX_DataProcessingAgreements_ExpiresAtUtc` (`ExpiresAtUtc`),
    INDEX `IX_DataProcessingAgreements_TenantId` (`TenantId`)
);
