CREATE TABLE IF NOT EXISTS `OperationAuditEntries` (
    `Id`                 CHAR(36)      NOT NULL,
    `CorrelationId`      VARCHAR(256)  NOT NULL,
    `UserId`             VARCHAR(256)  NULL,
    `TenantId`           VARCHAR(128)  NULL,
    `Action`             VARCHAR(128)  NOT NULL,
    `EntityType`         VARCHAR(256)  NOT NULL,
    `EntityId`           VARCHAR(256)  NULL,
    `Outcome`            INT           NOT NULL,
    `ErrorMessage`       VARCHAR(2048) NULL,
    `TimestampUtc`       DATETIME(6)   NOT NULL,
    `StartedAtUtc`       DATETIME(6)   NOT NULL,
    `CompletedAtUtc`     DATETIME(6)   NOT NULL,
    `IpAddress`          VARCHAR(45)   NULL,
    `UserAgent`          VARCHAR(512)  NULL,
    `RequestPayloadHash` VARCHAR(64)   NULL,
    `RequestPayload`     LONGTEXT      NULL,
    `ResponsePayload`    LONGTEXT      NULL,
    `Metadata`           LONGTEXT      NULL,

    PRIMARY KEY (`Id`),
    INDEX `IX_OperationAuditEntries_Entity` (`EntityType`, `EntityId`),
    INDEX `IX_OperationAuditEntries_Timestamp` (`TimestampUtc`),
    INDEX `IX_OperationAuditEntries_Outcome` (`Outcome`),
    INDEX `IX_OperationAuditEntries_UserId` (`UserId`),
    INDEX `IX_OperationAuditEntries_TenantId` (`TenantId`),
    INDEX `IX_OperationAuditEntries_CorrelationId` (`CorrelationId`),
    INDEX `IX_OperationAuditEntries_Action` (`Action`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
