using LanguageExt;

namespace Encina;

/// <summary>
/// Generates unique distributed identifiers with shard information embedded in the ID,
/// enabling reverse routing from an ID back to its originating shard.
/// </summary>
/// <typeparam name="TId">The strongly-typed ID value type produced by this generator.</typeparam>
/// <remarks>
/// <para>
/// This interface extends <see cref="IIdGenerator{TId}"/> to support the shard-embedded
/// ID pattern used by systems like Instagram (Snowflake with shard bits) and ShardingSphere.
/// </para>
/// <para>
/// The key advantage of shard-embedded IDs is that any service can determine which shard
/// owns an entity by inspecting the ID alone, without a separate shard key lookup. This
/// eliminates the need for a directory-based routing step in read paths.
/// </para>
/// <para>
/// All operations return <see cref="Either{EncinaError, T}"/> following the Railway
/// Oriented Programming pattern.
/// </para>
/// </remarks>
/// <example>
/// <code>
/// // Generate a shard-embedded ID and later extract the shard
/// public class OrderService(IShardedIdGenerator&lt;SnowflakeId&gt; idGen)
/// {
///     public Either&lt;EncinaError, Order&gt; CreateOrder(string shardId, CreateOrder cmd)
///     {
///         return idGen.Generate(shardId)
///             .Map(id => new Order(id, cmd.CustomerId));
///     }
///
///     public Either&lt;EncinaError, string&gt; GetShardForOrder(SnowflakeId orderId)
///     {
///         return idGen.ExtractShardId(orderId);
///     }
/// }
/// </code>
/// </example>
public interface IShardedIdGenerator<TId> : IIdGenerator<TId>
{
    /// <summary>
    /// Generates a new unique identifier with the specified shard ID embedded.
    /// </summary>
    /// <param name="shardId">
    /// The shard identifier to embed in the generated ID. Must not be null or empty.
    /// </param>
    /// <returns>
    /// Right with the generated ID containing the embedded shard information;
    /// Left with an <see cref="EncinaError"/> if generation fails
    /// (e.g., invalid shard ID, clock drift, sequence exhausted).
    /// </returns>
    Either<EncinaError, TId> Generate(string shardId);

    /// <summary>
    /// Extracts the shard identifier that was embedded in a previously generated ID.
    /// </summary>
    /// <param name="id">The ID from which to extract the shard identifier.</param>
    /// <returns>
    /// Right with the extracted shard ID string;
    /// Left with an <see cref="EncinaError"/> if extraction fails
    /// (e.g., the ID was not generated by a sharded generator, or the format is invalid).
    /// </returns>
    Either<EncinaError, string> ExtractShardId(TId id);
}
