using Encina.Compliance.Retention.Model;

using FsCheck;
using FsCheck.Fluent;
using FsCheck.Xunit;

namespace Encina.PropertyTests.Compliance.Retention;

/// <summary>
/// Property-based tests for <see cref="LegalHold"/> verifying domain invariants
/// using FsCheck random data generation.
/// </summary>
public class LegalHoldPropertyTests
{
    #region Create Factory Invariants

    /// <summary>
    /// Invariant: LegalHold.Create always generates a non-empty Id (GUID without hyphens, 32 chars).
    /// </summary>
    [Property(MaxTest = 50)]
    public bool Create_AlwaysGeneratesNonEmptyId(NonEmptyString entityId, NonEmptyString reason)
    {
        var hold = LegalHold.Create(
            entityId: entityId.Get,
            reason: reason.Get);

        return !string.IsNullOrEmpty(hold.Id) && hold.Id.Length == 32;
    }

    /// <summary>
    /// Invariant: The Id generated by Create contains no hyphens (N format GUID).
    /// </summary>
    [Property(MaxTest = 50)]
    public bool Create_IdContainsNoHyphens(NonEmptyString entityId, NonEmptyString reason)
    {
        var hold = LegalHold.Create(
            entityId: entityId.Get,
            reason: reason.Get);

        return !hold.Id.Contains('-');
    }

    /// <summary>
    /// Invariant: LegalHold.Create always sets IsActive to true (ReleasedAtUtc is null).
    /// </summary>
    [Property(MaxTest = 50)]
    public bool Create_AlwaysSetsIsActiveToTrue(NonEmptyString entityId, NonEmptyString reason)
    {
        var hold = LegalHold.Create(
            entityId: entityId.Get,
            reason: reason.Get);

        return hold.IsActive;
    }

    /// <summary>
    /// Invariant: LegalHold.Create always initializes ReleasedAtUtc to null (hold is active).
    /// </summary>
    [Property(MaxTest = 50)]
    public bool Create_ReleasedAtUtcDefaultsToNull(NonEmptyString entityId, NonEmptyString reason)
    {
        var hold = LegalHold.Create(
            entityId: entityId.Get,
            reason: reason.Get);

        return hold.ReleasedAtUtc is null;
    }

    /// <summary>
    /// Invariant: LegalHold.Create always initializes ReleasedByUserId to null.
    /// </summary>
    [Property(MaxTest = 50)]
    public bool Create_ReleasedByUserIdDefaultsToNull(NonEmptyString entityId, NonEmptyString reason)
    {
        var hold = LegalHold.Create(
            entityId: entityId.Get,
            reason: reason.Get);

        return hold.ReleasedByUserId is null;
    }

    /// <summary>
    /// Invariant: The EntityId property always matches the entityId parameter passed to Create.
    /// </summary>
    [Property(MaxTest = 50)]
    public bool Create_PreservesEntityId(NonEmptyString entityId, NonEmptyString reason)
    {
        var hold = LegalHold.Create(
            entityId: entityId.Get,
            reason: reason.Get);

        return hold.EntityId == entityId.Get;
    }

    /// <summary>
    /// Invariant: The Reason property always matches the reason parameter passed to Create.
    /// </summary>
    [Property(MaxTest = 50)]
    public bool Create_PreservesReason(NonEmptyString entityId, NonEmptyString reason)
    {
        var hold = LegalHold.Create(
            entityId: entityId.Get,
            reason: reason.Get);

        return hold.Reason == reason.Get;
    }

    /// <summary>
    /// Invariant: The optional appliedByUserId parameter is preserved when provided.
    /// </summary>
    [Property(MaxTest = 50)]
    public bool Create_PreservesAppliedByUserIdWhenProvided(
        NonEmptyString entityId,
        NonEmptyString reason,
        NonEmptyString userId)
    {
        var hold = LegalHold.Create(
            entityId: entityId.Get,
            reason: reason.Get,
            appliedByUserId: userId.Get);

        return hold.AppliedByUserId == userId.Get;
    }

    /// <summary>
    /// Invariant: Create always initializes AppliedByUserId to null when not provided.
    /// </summary>
    [Property(MaxTest = 50)]
    public bool Create_AppliedByUserIdDefaultsToNull(NonEmptyString entityId, NonEmptyString reason)
    {
        var hold = LegalHold.Create(
            entityId: entityId.Get,
            reason: reason.Get);

        return hold.AppliedByUserId is null;
    }

    /// <summary>
    /// Invariant: Different Create calls always produce unique Ids.
    /// </summary>
    [Property(MaxTest = 50)]
    public bool Create_DifferentCallsProduceUniqueIds(NonEmptyString entityId, NonEmptyString reason)
    {
        var hold1 = LegalHold.Create(entityId: entityId.Get, reason: reason.Get);
        var hold2 = LegalHold.Create(entityId: entityId.Get, reason: reason.Get);

        return hold1.Id != hold2.Id;
    }

    #endregion

    #region Released Hold Invariants

    /// <summary>
    /// Invariant: A hold with ReleasedAtUtc set always has IsActive equal to false.
    /// </summary>
    [Property(MaxTest = 50)]
    public bool ReleasedHold_IsActiveIsFalse(NonEmptyString entityId, NonEmptyString reason)
    {
        var hold = LegalHold.Create(
            entityId: entityId.Get,
            reason: reason.Get);

        var releasedHold = hold with
        {
            ReleasedAtUtc = DateTimeOffset.UtcNow,
            ReleasedByUserId = "legal-counsel"
        };

        return !releasedHold.IsActive;
    }

    /// <summary>
    /// Invariant: IsActive is always the inverse of (ReleasedAtUtc != null).
    /// For any LegalHold, IsActive == (ReleasedAtUtc is null) must always hold.
    /// </summary>
    [Property(MaxTest = 50)]
    public bool IsActive_AlwaysMatchesNullReleasedAtUtc(
        NonEmptyString entityId,
        NonEmptyString reason)
    {
        var activeHold = LegalHold.Create(
            entityId: entityId.Get,
            reason: reason.Get);

        var releasedHold = activeHold with
        {
            ReleasedAtUtc = DateTimeOffset.UtcNow
        };

        // Active hold: IsActive must be true, ReleasedAtUtc must be null
        var activeOk = activeHold.IsActive && activeHold.ReleasedAtUtc is null;

        // Released hold: IsActive must be false, ReleasedAtUtc must be non-null
        var releasedOk = !releasedHold.IsActive && releasedHold.ReleasedAtUtc is not null;

        return activeOk && releasedOk;
    }

    #endregion
}
