using Encina.Compliance.Retention.Model;

using FsCheck;
using FsCheck.Xunit;

namespace Encina.PropertyTests.Compliance.Retention;

/// <summary>
/// Property-based tests for <see cref="RetentionRecord"/> verifying domain invariants
/// using FsCheck random data generation.
/// </summary>
public class RetentionRecordPropertyTests
{
    #region Create Factory Invariants

    /// <summary>
    /// Invariant: RetentionRecord.Create always generates a non-empty Id (GUID without hyphens, 32 chars).
    /// </summary>
    [Property(MaxTest = 50)]
    public bool Create_AlwaysGeneratesNonEmptyId(NonEmptyString entityId, NonEmptyString category)
    {
        var record = RetentionRecord.Create(
            entityId: entityId.Get,
            dataCategory: category.Get,
            createdAtUtc: DateTimeOffset.UtcNow,
            expiresAtUtc: DateTimeOffset.UtcNow.AddDays(30));

        return !string.IsNullOrEmpty(record.Id) && record.Id.Length == 32;
    }

    /// <summary>
    /// Invariant: The Id generated by Create contains no hyphens (N format GUID).
    /// </summary>
    [Property(MaxTest = 50)]
    public bool Create_IdContainsNoHyphens(NonEmptyString entityId, NonEmptyString category)
    {
        var record = RetentionRecord.Create(
            entityId: entityId.Get,
            dataCategory: category.Get,
            createdAtUtc: DateTimeOffset.UtcNow,
            expiresAtUtc: DateTimeOffset.UtcNow.AddDays(30));

        return !record.Id.Contains('-');
    }

    /// <summary>
    /// Invariant: RetentionRecord.Create always sets Status to Active.
    /// </summary>
    [Property(MaxTest = 50)]
    public bool Create_AlwaysSetsStatusToActive(NonEmptyString entityId, NonEmptyString category)
    {
        var record = RetentionRecord.Create(
            entityId: entityId.Get,
            dataCategory: category.Get,
            createdAtUtc: DateTimeOffset.UtcNow,
            expiresAtUtc: DateTimeOffset.UtcNow.AddDays(30));

        return record.Status == RetentionStatus.Active;
    }

    /// <summary>
    /// Invariant: The EntityId property always matches the entityId parameter passed to Create.
    /// </summary>
    [Property(MaxTest = 50)]
    public bool Create_PreservesEntityId(NonEmptyString entityId, NonEmptyString category)
    {
        var record = RetentionRecord.Create(
            entityId: entityId.Get,
            dataCategory: category.Get,
            createdAtUtc: DateTimeOffset.UtcNow,
            expiresAtUtc: DateTimeOffset.UtcNow.AddDays(30));

        return record.EntityId == entityId.Get;
    }

    /// <summary>
    /// Invariant: The DataCategory property always matches the dataCategory parameter passed to Create.
    /// </summary>
    [Property(MaxTest = 50)]
    public bool Create_PreservesDataCategory(NonEmptyString entityId, NonEmptyString category)
    {
        var record = RetentionRecord.Create(
            entityId: entityId.Get,
            dataCategory: category.Get,
            createdAtUtc: DateTimeOffset.UtcNow,
            expiresAtUtc: DateTimeOffset.UtcNow.AddDays(30));

        return record.DataCategory == category.Get;
    }

    /// <summary>
    /// Invariant: The ExpiresAtUtc property is always >= CreatedAtUtc when created with a positive offset.
    /// </summary>
    [Property(MaxTest = 50)]
    public bool Create_ExpiresAtUtcAlwaysGreaterOrEqualToCreatedAtUtc(
        NonEmptyString entityId,
        NonEmptyString category,
        PositiveInt daysOffset)
    {
        var createdAt = DateTimeOffset.UtcNow;
        var expiresAt = createdAt.AddDays(daysOffset.Get);

        var record = RetentionRecord.Create(
            entityId: entityId.Get,
            dataCategory: category.Get,
            createdAtUtc: createdAt,
            expiresAtUtc: expiresAt);

        return record.ExpiresAtUtc >= record.CreatedAtUtc;
    }

    /// <summary>
    /// Invariant: Create always initializes DeletedAtUtc to null (data has not yet been deleted).
    /// </summary>
    [Property(MaxTest = 50)]
    public bool Create_DeletedAtUtcDefaultsToNull(NonEmptyString entityId, NonEmptyString category)
    {
        var record = RetentionRecord.Create(
            entityId: entityId.Get,
            dataCategory: category.Get,
            createdAtUtc: DateTimeOffset.UtcNow,
            expiresAtUtc: DateTimeOffset.UtcNow.AddDays(30));

        return record.DeletedAtUtc is null;
    }

    /// <summary>
    /// Invariant: Create always initializes LegalHoldId to null (no hold applied at creation).
    /// </summary>
    [Property(MaxTest = 50)]
    public bool Create_LegalHoldIdDefaultsToNull(NonEmptyString entityId, NonEmptyString category)
    {
        var record = RetentionRecord.Create(
            entityId: entityId.Get,
            dataCategory: category.Get,
            createdAtUtc: DateTimeOffset.UtcNow,
            expiresAtUtc: DateTimeOffset.UtcNow.AddDays(30));

        return record.LegalHoldId is null;
    }

    /// <summary>
    /// Invariant: Create with different inputs always produces unique Ids.
    /// </summary>
    [Property(MaxTest = 50)]
    public bool Create_DifferentCallsProduceUniqueIds(NonEmptyString entityId, NonEmptyString category)
    {
        var now = DateTimeOffset.UtcNow;
        var expires = now.AddDays(30);

        var record1 = RetentionRecord.Create(
            entityId: entityId.Get,
            dataCategory: category.Get,
            createdAtUtc: now,
            expiresAtUtc: expires);

        var record2 = RetentionRecord.Create(
            entityId: entityId.Get,
            dataCategory: category.Get,
            createdAtUtc: now,
            expiresAtUtc: expires);

        return record1.Id != record2.Id;
    }

    /// <summary>
    /// Invariant: The optional policyId parameter is preserved when provided.
    /// </summary>
    [Property(MaxTest = 50)]
    public bool Create_PreservesPolicyIdWhenProvided(
        NonEmptyString entityId,
        NonEmptyString category,
        NonEmptyString policyId)
    {
        var record = RetentionRecord.Create(
            entityId: entityId.Get,
            dataCategory: category.Get,
            createdAtUtc: DateTimeOffset.UtcNow,
            expiresAtUtc: DateTimeOffset.UtcNow.AddDays(30),
            policyId: policyId.Get);

        return record.PolicyId == policyId.Get;
    }

    #endregion
}
