using Encina.Compliance.Retention.Model;

using FsCheck;
using FsCheck.Fluent;
using FsCheck.Xunit;

namespace Encina.PropertyTests.Compliance.Retention;

/// <summary>
/// Property-based tests for <see cref="RetentionPolicy"/> verifying domain invariants
/// using FsCheck random data generation.
/// </summary>
public class RetentionPolicyPropertyTests
{
    #region Create Factory Invariants

    /// <summary>
    /// Invariant: RetentionPolicy.Create always generates a non-empty Id (GUID without hyphens, 32 chars).
    /// </summary>
    [Property(MaxTest = 50)]
    public bool Create_AlwaysGeneratesNonEmptyId(NonEmptyString category)
    {
        var policy = RetentionPolicy.Create(
            dataCategory: category.Get,
            retentionPeriod: TimeSpan.FromDays(30));

        return !string.IsNullOrEmpty(policy.Id) && policy.Id.Length == 32;
    }

    /// <summary>
    /// Invariant: The Id generated by Create contains no hyphens (N format GUID).
    /// </summary>
    [Property(MaxTest = 50)]
    public bool Create_IdContainsNoHyphens(NonEmptyString category)
    {
        var policy = RetentionPolicy.Create(
            dataCategory: category.Get,
            retentionPeriod: TimeSpan.FromDays(30));

        return !policy.Id.Contains('-');
    }

    /// <summary>
    /// Invariant: Create with a positive retention period always preserves the period exactly.
    /// </summary>
    [Property(MaxTest = 50)]
    public bool Create_WithPositiveRetentionPeriod_PreservesIt(
        NonEmptyString category,
        PositiveInt days)
    {
        var period = TimeSpan.FromDays(days.Get);
        var policy = RetentionPolicy.Create(
            dataCategory: category.Get,
            retentionPeriod: period);

        return policy.RetentionPeriod == period;
    }

    /// <summary>
    /// Invariant: The DataCategory property always matches the dataCategory parameter passed to Create.
    /// </summary>
    [Property(MaxTest = 50)]
    public bool Create_PreservesDataCategory(NonEmptyString category)
    {
        var policy = RetentionPolicy.Create(
            dataCategory: category.Get,
            retentionPeriod: TimeSpan.FromDays(30));

        return policy.DataCategory == category.Get;
    }

    /// <summary>
    /// Invariant: Create always defaults AutoDelete to true when not provided.
    /// </summary>
    [Property(MaxTest = 50)]
    public bool Create_DefaultsAutoDeleteToTrue(NonEmptyString category)
    {
        var policy = RetentionPolicy.Create(
            dataCategory: category.Get,
            retentionPeriod: TimeSpan.FromDays(30));

        return policy.AutoDelete;
    }

    /// <summary>
    /// Invariant: Create always defaults PolicyType to TimeBased when not provided.
    /// </summary>
    [Property(MaxTest = 50)]
    public bool Create_DefaultsPolicyTypeToTimeBased(NonEmptyString category)
    {
        var policy = RetentionPolicy.Create(
            dataCategory: category.Get,
            retentionPeriod: TimeSpan.FromDays(30));

        return policy.PolicyType == RetentionPolicyType.TimeBased;
    }

    /// <summary>
    /// Invariant: Create always initializes LastModifiedAtUtc to null (policy is new, not yet modified).
    /// </summary>
    [Property(MaxTest = 50)]
    public bool Create_LastModifiedAtUtcDefaultsToNull(NonEmptyString category)
    {
        var policy = RetentionPolicy.Create(
            dataCategory: category.Get,
            retentionPeriod: TimeSpan.FromDays(30));

        return policy.LastModifiedAtUtc is null;
    }

    /// <summary>
    /// Invariant: The AutoDelete flag is preserved when explicitly set to false.
    /// </summary>
    [Property(MaxTest = 50)]
    public bool Create_PreservesAutoDeleteFalse(NonEmptyString category)
    {
        var policy = RetentionPolicy.Create(
            dataCategory: category.Get,
            retentionPeriod: TimeSpan.FromDays(30),
            autoDelete: false);

        return !policy.AutoDelete;
    }

    /// <summary>
    /// Invariant: Different Create calls always produce unique Ids.
    /// </summary>
    [Property(MaxTest = 50)]
    public bool Create_DifferentCallsProduceUniqueIds(NonEmptyString category)
    {
        var period = TimeSpan.FromDays(30);

        var policy1 = RetentionPolicy.Create(
            dataCategory: category.Get,
            retentionPeriod: period);

        var policy2 = RetentionPolicy.Create(
            dataCategory: category.Get,
            retentionPeriod: period);

        return policy1.Id != policy2.Id;
    }

    #endregion

    #region FromDays / FromYears Helper Invariants

    /// <summary>
    /// Invariant: FromDays always returns a non-negative TimeSpan for positive input.
    /// </summary>
    [Property(MaxTest = 100)]
    public bool FromDays_AlwaysReturnsNonNegativeTimeSpan(PositiveInt days)
    {
        var result = RetentionPolicy.FromDays(days.Get);
        return result >= TimeSpan.Zero;
    }

    /// <summary>
    /// Invariant: FromDays preserves the exact day count.
    /// </summary>
    [Property(MaxTest = 100)]
    public bool FromDays_PreservesExactDayCount(PositiveInt days)
    {
        var result = RetentionPolicy.FromDays(days.Get);
        return result.TotalDays == days.Get;
    }

    /// <summary>
    /// Invariant: FromYears(n) always equals FromDays(n * 365) for any positive n.
    /// </summary>
    [Property(MaxTest = 100)]
    public bool FromYears_EqualsFromDaysTimesThreeHundredSixtyFive(PositiveInt years)
    {
        var fromYears = RetentionPolicy.FromYears(years.Get);
        var fromDays = RetentionPolicy.FromDays(years.Get * 365);
        return fromYears == fromDays;
    }

    /// <summary>
    /// Invariant: FromYears always returns a non-negative TimeSpan for positive input.
    /// </summary>
    [Property(MaxTest = 100)]
    public bool FromYears_AlwaysReturnsNonNegativeTimeSpan(PositiveInt years)
    {
        var result = RetentionPolicy.FromYears(years.Get);
        return result >= TimeSpan.Zero;
    }

    /// <summary>
    /// Invariant: FromYears(n) is always greater than FromYears(n-1) for n > 1.
    /// </summary>
    [Property(MaxTest = 50)]
    public Property FromYears_IsMonotonicallyIncreasing()
    {
        return Prop.ForAll(
            Gen.Choose(2, 100).ToArbitrary(),
            n =>
            {
                var larger = RetentionPolicy.FromYears(n);
                var smaller = RetentionPolicy.FromYears(n - 1);
                return larger > smaller;
            });
    }

    #endregion

    #region PolicyType Invariants

    /// <summary>
    /// Invariant: All RetentionPolicyType values can be used when creating a policy.
    /// </summary>
    [Property(MaxTest = 50)]
    public Property Create_PreservesPolicyTypeForAllEnumValues()
    {
        var policyTypeGen = Gen.Elements(
            RetentionPolicyType.TimeBased,
            RetentionPolicyType.EventBased,
            RetentionPolicyType.ConsentBased);

        return Prop.ForAll(
            Arb.From(policyTypeGen),
            policyType =>
            {
                var policy = RetentionPolicy.Create(
                    dataCategory: $"cat-{Guid.NewGuid():N}",
                    retentionPeriod: TimeSpan.FromDays(30),
                    policyType: policyType);

                policy.PolicyType.ShouldBe(policyType);
            });
    }

    #endregion
}
