using Encina.Messaging.RoutingSlip;
using LanguageExt;
using Shouldly;
using static LanguageExt.Prelude;

namespace Encina.Tests.RoutingSlip;

public sealed class RoutingSlipBuilderTests
{
    [Fact]
    public void Create_WithValidSlipType_CreatesBuilder()
    {
        // Act
        var builder = RoutingSlipBuilder.Create<TestData>("TestSlip");

        // Assert
        builder.ShouldNotBeNull();
        builder.SlipType.ShouldBe("TestSlip");
    }

    [Theory]
    [InlineData(null)]
    [InlineData("")]
    [InlineData("   ")]
    public void Create_WithInvalidSlipType_ThrowsArgumentException(string? slipType)
    {
        // Act & Assert
        Should.Throw<ArgumentException>(() =>
            RoutingSlipBuilder.Create<TestData>(slipType!));
    }

    [Fact]
    public void Step_ReturnsStepBuilder()
    {
        // Arrange
        var builder = RoutingSlipBuilder.Create<TestData>("TestSlip");

        // Act
        var stepBuilder = builder.Step("Step1");

        // Assert
        stepBuilder.ShouldNotBeNull();
    }

    [Fact]
    public void Step_WithoutName_UsesAutoGeneratedName()
    {
        // Arrange & Act
        var definition = RoutingSlipBuilder.Create<TestData>("TestSlip")
            .Step()
            .Execute((data, ct) => ValueTask.FromResult(Right<EncinaError, TestData>(data)))
            .Build();

        // Assert
        definition.Steps[0].Name.ShouldBe("Step 1");
    }

    [Fact]
    public void Build_WithNoSteps_ThrowsInvalidOperationException()
    {
        // Arrange
        var builder = RoutingSlipBuilder.Create<TestData>("TestSlip");

        // Act & Assert
        Should.Throw<InvalidOperationException>(() => builder.Build());
    }

    [Fact]
    public void Build_WithSingleStep_ReturnsDefinition()
    {
        // Arrange & Act
        var definition = RoutingSlipBuilder.Create<TestData>("TestSlip")
            .Step("Step1")
            .Execute((data, ct) => ValueTask.FromResult(Right<EncinaError, TestData>(data)))
            .Build();

        // Assert
        definition.ShouldNotBeNull();
        definition.SlipType.ShouldBe("TestSlip");
        definition.Steps.Count.ShouldBe(1);
        definition.Steps[0].Name.ShouldBe("Step1");
    }

    [Fact]
    public void Build_WithMultipleSteps_ReturnsAllSteps()
    {
        // Arrange & Act
        var definition = RoutingSlipBuilder.Create<TestData>("TestSlip")
            .Step("Step1")
            .Execute((data, ct) => ValueTask.FromResult(Right<EncinaError, TestData>(data)))
            .Step("Step2")
            .Execute((data, ct) => ValueTask.FromResult(Right<EncinaError, TestData>(data)))
            .Step("Step3")
            .Execute((data, ct) => ValueTask.FromResult(Right<EncinaError, TestData>(data)))
            .Build();

        // Assert
        definition.Steps.Count.ShouldBe(3);
        definition.Steps[0].Name.ShouldBe("Step1");
        definition.Steps[1].Name.ShouldBe("Step2");
        definition.Steps[2].Name.ShouldBe("Step3");
    }

    [Fact]
    public void Build_WithTimeout_SetsTimeout()
    {
        // Arrange & Act
        var definition = RoutingSlipBuilder.Create<TestData>("TestSlip")
            .Step("Step1")
            .Execute((data, ct) => ValueTask.FromResult(Right<EncinaError, TestData>(data)))
            .WithTimeout(TimeSpan.FromMinutes(5))
            .Build();

        // Assert
        definition.Timeout.ShouldBe(TimeSpan.FromMinutes(5));
    }

    [Fact]
    public void WithTimeout_WithZeroOrNegative_ThrowsArgumentOutOfRangeException()
    {
        // Arrange
        var builder = RoutingSlipBuilder.Create<TestData>("TestSlip")
            .Step("Step1")
            .Execute((data, ct) => ValueTask.FromResult(Right<EncinaError, TestData>(data)));

        // Act & Assert
        Should.Throw<ArgumentOutOfRangeException>(() => builder.WithTimeout(TimeSpan.Zero));
        Should.Throw<ArgumentOutOfRangeException>(() => builder.WithTimeout(TimeSpan.FromMinutes(-1)));
    }

    [Fact]
    public void Build_WithOnCompletion_SetsCompletionHandler()
    {
        // Act
        var definition = RoutingSlipBuilder.Create<TestData>("TestSlip")
            .Step("Step1")
            .Execute((data, ct) => ValueTask.FromResult(Right<EncinaError, TestData>(data)))
            .OnCompletion((data, ctx, ct) => Task.CompletedTask)
            .Build();

        // Assert
        definition.OnCompletion.ShouldNotBeNull();
    }

    [Fact]
    public void Build_WithOnCompletionSimplified_SetsCompletionHandler()
    {
        // Arrange & Act - Using simplified overload on RoutingSlipBuilder
        var definition = RoutingSlipBuilder.Create<TestData>("TestSlip")
            .Step("Step1")
            .Execute((data, ct) => ValueTask.FromResult(Right<EncinaError, TestData>(data)))
            .Build();

        // Build a new one with the simplified overload via RoutingSlipBuilder
        var definition2 = RoutingSlipBuilder.Create<TestData>("TestSlip")
            .OnCompletion((data, ct) => Task.CompletedTask)
            .Step("Step1")
            .Execute((data, ct) => ValueTask.FromResult(Right<EncinaError, TestData>(data)))
            .Build();

        // Assert
        definition2.OnCompletion.ShouldNotBeNull();
    }

    [Fact]
    public void OnCompletion_WithNullHandler_ThrowsArgumentNullException()
    {
        // Arrange - Get parent builder to test OnCompletion null check
        var builder = RoutingSlipBuilder.Create<TestData>("TestSlip");

        // Act & Assert
        Should.Throw<ArgumentNullException>(() =>
            builder.OnCompletion((Func<TestData, RoutingSlipContext<TestData>, CancellationToken, Task>)null!));
    }

    [Fact]
    public void InitialStepCount_ReturnsCorrectCount()
    {
        // Arrange & Act
        var definition = RoutingSlipBuilder.Create<TestData>("TestSlip")
            .Step("Step1")
            .Execute((data, ct) => ValueTask.FromResult(Right<EncinaError, TestData>(data)))
            .Step("Step2")
            .Execute((data, ct) => ValueTask.FromResult(Right<EncinaError, TestData>(data)))
            .Build();

        // Assert
        definition.InitialStepCount.ShouldBe(2);
    }

    private sealed class TestData
    {
        public Guid Id { get; set; }
        public string? Value { get; set; }
    }
}
