# Regression suite for the PreToolUse hooks in .claude/hooks. Feeds each case to the hook the way Claude Code
# does (tool-call JSON on stdin) and compares the exit code: 0 = allowed, 2 = blocked.
#
# Usage: pwsh -NoProfile -File .claude/hooks/tests/Test-Hooks.ps1        (exit code 1 when any case fails)

$ErrorActionPreference = 'Stop'
$hooks = Split-Path -Parent $PSScriptRoot
$repo = Split-Path -Parent (Split-Path -Parent $hooks)
$attribution = Join-Path $hooks 'block-ai-attribution.ps1'
$issue = Join-Path $hooks 'check-issue-template.ps1'

$work = Join-Path ([IO.Path]::GetTempPath()) "encina-hook-tests-$PID"
$sub = Join-Path $work 'sub dir'
New-Item -ItemType Directory -Force $sub | Out-Null
$env:CLAUDE_PROJECT_DIR = $repo

# Assembled so this file never contains the literal patterns the attribution hook blocks.
$trailer = 'Co-Authored-By: ' + 'Claude Opus <noreply@' + 'anthropic.com>'
$generated = 'Generated with ' + '[Claude Code](https://claude.com/claude-code)'

Set-Content (Join-Path $work 'msg-bad.txt') "fix: thing`n`n$trailer"
Set-Content (Join-Path $work 'msg-ok.txt') "fix: thing`n`nPlain body."
Set-Content (Join-Path $sub 'msg-bad.txt') "fix: thing`n`n$trailer"

$debt = @'
## Type
- [x] Code smell
## Description
d
## Location
l
## Current Behavior
c
## Expected Behavior
e
## Root Cause
r
## Proposed Fix
p
## Priority
- [x] Medium
## Effort Estimate
- [x] Small
## Related Issues
- #1
'@
Set-Content (Join-Path $work 'debt-ok.md') $debt
Set-Content (Join-Path $work 'debt-missing.md') ($debt -replace '## Root Cause\r?\nr\r?\n', '')
Set-Content (Join-Path $work 'debt-order.md') ($debt -replace '## Type', '## TMP' -replace '## Related Issues', '## Type' -replace '## TMP', '## Related Issues')
Set-Content (Join-Path $work 'debt-case.md') ($debt -replace '## Expected Behavior', '## Expected behavior')
Set-Content (Join-Path $work 'debt-quoted.md') ($debt -replace '(## Description\r?\n)d', "`$1d`n``````md`n## Related Issues`n``````")
Set-Content (Join-Path $work 'free.md') "## Summary`nx`n## Proposed fix`ny"
Set-Content (Join-Path $work 'free-fenced.md') "Free form.`n``````md`n$($debt)`n``````"

$cases = @(
    # hook, tool, command, expected, label
    @($attribution, 'PowerShell', "git commit -m `"fix: x`" -m `"$trailer`"", 2, 'inline trailer'),
    @($attribution, 'PowerShell', 'git commit -F msg-bad.txt', 2, 'trailer in -F file'),
    @($attribution, 'PowerShell', 'git commit -F msg-ok.txt', 0, 'clean -F file'),
    @($attribution, 'PowerShell', 'git commit -m "fix: plain"', 0, 'clean inline commit'),
    @($attribution, 'PowerShell', "gh pr create --title t --body `"x`n`n$generated`"", 2, 'generated-with line in PR body'),
    @($attribution, 'PowerShell', 'gh pr create --title t --body-file msg-bad.txt', 2, 'trailer in PR body file'),
    @($attribution, 'PowerShell', 'gh pr edit 5 --body-file msg-ok.txt', 0, 'clean PR body file'),
    @($attribution, 'PowerShell', "git log --grep `"$trailer`"", 0, 'git log is not a commit'),
    @($attribution, 'PowerShell', 'dotnet build', 0, 'unrelated command'),
    @($attribution, 'PowerShell', "git --no-pager commit -m `"$trailer`"", 2, 'git --no-pager commit'),
    @($attribution, 'PowerShell', "git -c a.b=1 -c c.d=2 commit -m `"$trailer`"", 2, 'git -c k=v twice'),
    @($attribution, 'PowerShell', "git -C `"sub dir`" commit -m `"$trailer`"", 2, 'git -C quoted dir'),
    @($attribution, 'PowerShell', "git.exe commit -m `"$trailer`"", 2, 'git.exe'),
    @($attribution, 'PowerShell', "gh pr merge 5 --squash --body `"$trailer`"", 2, 'gh pr merge --body'),
    @($attribution, 'PowerShell', "git commit -m `"feat: x`" --trailer `"Co-authored-by=Claude`"", 2, '--trailer with ='),
    @($attribution, 'PowerShell', "gh pr create -t t --body `"Generated by Claude Code`"", 2, 'generated by'),
    @($attribution, 'PowerShell', "git commit -m `"Assisted-by: Claude`"", 2, 'assisted-by trailer'),
    @($attribution, 'PowerShell', 'git -C "sub dir" commit -F msg-bad.txt', 2, 'relative -F under git -C'),
    @($attribution, 'PowerShell', 'Set-Location "sub dir"; git commit -F msg-bad.txt', 2, 'relative -F after Set-Location'),
    @($attribution, 'PowerShell', 'git commit --template=msg-bad.txt', 2, '--template file'),
    @($attribution, 'PowerShell', "Select-String -Path CLAUDE.md -Pattern `"$trailer`"; git commit -m `"docs: tidy`"", 0, 'pattern in another statement'),
    @($attribution, 'Bash', "git commit -m `"`$(cat <<'EOF'`nfix: x`n`n$trailer`nEOF`n)`"", 2, 'bash heredoc message'),
    @($attribution, 'Bash', "git commit -m `"`$(cat <<'EOF'`nfix: \`"quoted\`" (paren`nEOF`n)`"", 0, 'bash heredoc clean with quotes and paren'),
    @($attribution, 'PowerShell', "git commit -m @`"`nfix: x`n`n$trailer`n`"@", 2, 'PowerShell here-string message'),
    @($attribution, 'PowerShell', 'not json', 0, 'malformed payload'),

    @($issue, 'PowerShell', 'gh issue create --title "[DEBT] x" --body-file debt-ok.md', 0, 'DEBT complete'),
    @($issue, 'PowerShell', 'gh issue create --title "[DEBT] x" --body-file debt-missing.md', 2, 'DEBT missing Root Cause'),
    @($issue, 'PowerShell', 'gh issue create --title "[DEBT] x" --body-file debt-order.md', 2, 'DEBT out of order'),
    @($issue, 'PowerShell', 'gh issue create --title "[DEBT] x" --body-file free.md', 2, 'free-form body'),
    @($issue, 'PowerShell', 'gh issue create --title "[TECH-DEBT] x" --body-file debt-ok.md', 2, 'non-normalised prefix'),
    @($issue, 'PowerShell', 'gh issue create --title "No prefix" --body-file debt-ok.md', 2, 'no prefix'),
    @($issue, 'PowerShell', "gh issue create --title `"[DEBT] x`" --body `"$($debt -replace '"', '')`"", 0, 'inline body complete'),
    @($issue, 'PowerShell', "gh issue create --title '[DEBT] x' --body-file debt-ok.md", 0, 'single-quoted title'),
    @($issue, 'PowerShell', 'gh issue create --title $title --body-file $f', 0, 'variables'),
    @($issue, 'PowerShell', 'gh issue create --title "[DEBT] x" --body $body', 0, 'inline body from variable'),
    @($issue, 'PowerShell', 'gh issue create --title "[DEBT] x" --body (Get-Content b.md -Raw)', 0, 'inline body from subexpression'),
    @($issue, 'PowerShell', 'gh issue create --title "[DEBT] x" --body "$(cat b.md)"', 0, 'inline body from $()'),
    @($issue, 'PowerShell', 'gh issue create --repo stryker-mutator/stryker-net --title "Crash on xUnit v3" --body-file free.md', 0, 'other repository'),
    @($issue, 'PowerShell', 'gh issue create -R dlrivada/Encina --title "No prefix" --body-file debt-ok.md', 2, 'explicit Encina repository'),
    @($issue, 'PowerShell', "Select-String -Path x.md -Pattern 'gh issue create --title `"x`"'", 0, 'mentioned inside a string'),
    @($issue, 'PowerShell', 'git checkout -b fix/x; gh issue create --title "[DEBT] x" --template "Technical Debt"', 0, '--template after another statement'),
    @($issue, 'PowerShell', 'git commit -F msg-ok.txt && gh issue create --title "[DEBT] x" --body-file debt-ok.md', 0, '-F of an earlier git statement'),
    @($issue, 'PowerShell', 'gh issue create --title "[DEBT] x" --body "Free form. Repro: git commit -F msg.txt fails"', 2, '-F inside the body text'),
    @($issue, 'PowerShell', 'gh issue create --title "[DEBT] x" --body-file free-fenced.md', 2, 'headers only inside a fence'),
    @($issue, 'PowerShell', 'gh issue create --title "[DEBT] x" --body-file debt-quoted.md', 0, 'fenced header quoted in a valid body'),
    @($issue, 'PowerShell', 'gh issue create --title "[DEBT] x" --body-file debt-case.md', 2, 'header case differs'),
    @($issue, 'PowerShell', 'gh issue list --label bug', 0, 'not issue create'),
    @($issue, 'PowerShell', 'not json', 0, 'malformed payload')
)

$failed = 0
Push-Location $work
try {
    foreach ($case in $cases) {
        $hook, $tool, $command, $expected, $label = $case
        $json = if ($command -eq 'not json') { 'not json' } else { @{ tool_name = $tool; cwd = $work; tool_input = @{ command = $command } } | ConvertTo-Json -Compress }
        $stderr = $json | pwsh -NoProfile -File $hook 2>&1
        $code = $LASTEXITCODE
        $ok = $code -eq $expected
        if (-not $ok) { $failed++ }
        "{0} [{1}, expected {2}] {3}: {4}" -f ($(if ($ok) { 'PASS' } else { 'FAIL' })), $code, $expected, (Split-Path -Leaf $hook), $label
        if (-not $ok -and $stderr) { "      $stderr" }
    }
}
finally {
    Pop-Location
    Remove-Item -Recurse -Force $work
}

"{0} cases, {1} failed" -f $cases.Count, $failed
exit ([int]($failed -gt 0))
