# Regression suite for the PreToolUse hooks in .claude/hooks. Feeds each case to the hook the way Claude Code
# does (tool-call JSON on stdin) and compares the exit code: 0 = allowed, 2 = blocked.
#
# Usage: pwsh -NoProfile -File .claude/hooks/tests/Test-Hooks.ps1        (exit code 1 when any case fails)

$ErrorActionPreference = 'Stop'
$hooks = Split-Path -Parent $PSScriptRoot
$repo = Split-Path -Parent (Split-Path -Parent $hooks)
$attribution = Join-Path $hooks 'block-ai-attribution.ps1'
$issue = Join-Path $hooks 'check-issue-template.ps1'
$publish = Join-Path $hooks 'block-worker-publish.ps1'
$spawn = Join-Path $hooks 'block-worker-spawn.ps1'
$mainCheckout = Join-Path $hooks 'block-main-checkout-writes.ps1'

$work = Join-Path ([IO.Path]::GetTempPath()) "encina-hook-tests-$PID"
$sub = Join-Path $work 'sub dir'
New-Item -ItemType Directory -Force $sub | Out-Null
$env:CLAUDE_PROJECT_DIR = $repo

# Assembled so this file never contains the literal patterns the attribution hook blocks.
$trailer = 'Co-Authored-By: ' + 'Claude Opus <noreply@' + 'anthropic.com>'
$generated = 'Generated with ' + '[Claude Code](https://claude.com/claude-code)'

Set-Content (Join-Path $work 'msg-bad.txt') "fix: thing`n`n$trailer"
Set-Content (Join-Path $work 'msg-ok.txt') "fix: thing`n`nPlain body."
Set-Content (Join-Path $sub 'msg-bad.txt') "fix: thing`n`n$trailer"

$debt = @'
## Type
- [x] Code smell
## Description
d
## Location
l
## Current Behavior
c
## Expected Behavior
e
## Root Cause
r
## Proposed Fix
p
## Priority
- [x] Medium
## Effort Estimate
- [x] Small
## Related Issues
- #1
'@
Set-Content (Join-Path $work 'debt-ok.md') $debt
Set-Content (Join-Path $work 'debt-missing.md') ($debt -replace '## Root Cause\r?\nr\r?\n', '')
Set-Content (Join-Path $work 'debt-order.md') ($debt -replace '## Type', '## TMP' -replace '## Related Issues', '## Type' -replace '## TMP', '## Related Issues')
Set-Content (Join-Path $work 'debt-case.md') ($debt -replace '## Expected Behavior', '## Expected behavior')
Set-Content (Join-Path $work 'debt-quoted.md') ($debt -replace '(## Description\r?\n)d', "`$1d`n``````md`n## Related Issues`n``````")
Set-Content (Join-Path $work 'free.md') "## Summary`nx`n## Proposed fix`ny"
# A line starting with ``` whose info string contains a backtick is inline code, not a fence (CommonMark).
Set-Content (Join-Path $work 'debt-infostring.md') ($debt -replace '(## Description\r?\n)d', "`$1`````` inline ``code`` ``````")
Set-Content (Join-Path $work 'free-fenced.md') "Free form.`n``````md`n$($debt)`n``````"

$cases = @(
    # hook, tool, command, expected, label
    @($attribution, 'PowerShell', "git commit -m `"fix: x`" -m `"$trailer`"", 2, 'inline trailer'),
    @($attribution, 'PowerShell', 'git commit -F msg-bad.txt', 2, 'trailer in -F file'),
    @($attribution, 'PowerShell', 'git commit -F msg-ok.txt', 0, 'clean -F file'),
    @($attribution, 'PowerShell', 'git commit -m "fix: plain"', 0, 'clean inline commit'),
    @($attribution, 'PowerShell', "gh pr create --title t --body `"x`n`n$generated`"", 2, 'generated-with line in PR body'),
    @($attribution, 'PowerShell', 'gh pr create --title t --body-file msg-bad.txt', 2, 'trailer in PR body file'),
    @($attribution, 'PowerShell', 'gh pr edit 5 --body-file msg-ok.txt', 0, 'clean PR body file'),
    @($attribution, 'PowerShell', "git log --grep `"$trailer`"", 0, 'git log is not a commit'),
    @($attribution, 'PowerShell', 'dotnet build', 0, 'unrelated command'),
    @($attribution, 'PowerShell', "git --no-pager commit -m `"$trailer`"", 2, 'git --no-pager commit'),
    @($attribution, 'PowerShell', "git -c a.b=1 -c c.d=2 commit -m `"$trailer`"", 2, 'git -c k=v twice'),
    @($attribution, 'PowerShell', "git -C `"sub dir`" commit -m `"$trailer`"", 2, 'git -C quoted dir'),
    @($attribution, 'PowerShell', "git.exe commit -m `"$trailer`"", 2, 'git.exe'),
    @($attribution, 'PowerShell', "gh pr merge 5 --squash --body `"$trailer`"", 2, 'gh pr merge --body'),
    @($attribution, 'PowerShell', "git commit -m `"feat: x`" --trailer `"Co-authored-by=Claude`"", 2, '--trailer with ='),
    @($attribution, 'PowerShell', "gh pr create -t t --body `"Generated by Claude Code`"", 2, 'generated by'),
    @($attribution, 'PowerShell', "git commit -m `"Assisted-by: Claude`"", 2, 'assisted-by trailer'),
    @($attribution, 'PowerShell', 'git -C "sub dir" commit -F msg-bad.txt', 2, 'relative -F under git -C'),
    @($attribution, 'PowerShell', 'Set-Location "sub dir"; git commit -F msg-bad.txt', 2, 'relative -F after Set-Location'),
    @($attribution, 'PowerShell', 'git commit --template=msg-bad.txt', 2, '--template file'),
    @($attribution, 'PowerShell', "Select-String -Path CLAUDE.md -Pattern `"$trailer`"; git commit -m `"docs: tidy`"", 0, 'pattern in another statement'),
    @($attribution, 'Bash', "git commit -m `"`$(cat <<'EOF'`nfix: x`n`n$trailer`nEOF`n)`"", 2, 'bash heredoc message'),
    @($attribution, 'Bash', "git commit -m `"`$(cat <<'EOF'`nfix: \`"quoted\`" (paren`nEOF`n)`"", 0, 'bash heredoc clean with quotes and paren'),
    @($attribution, 'PowerShell', "git commit -m @`"`nfix: x`n`n$trailer`n`"@", 2, 'PowerShell here-string message'),
    @($attribution, 'PowerShell', 'not json', 0, 'malformed payload'),
    @($attribution, 'PowerShell', "git comm``it -m `"$trailer`"", 2, 'backtick-escaped verb'),
    @($attribution, 'PowerShell', "git commit ``-m `"$trailer`"", 2, 'backtick-escaped option'),
    @($attribution, 'PowerShell', "git commit ```n  -m `"$trailer`"", 2, 'line continuation'),
    @($attribution, 'PowerShell', "& `"git`" commit -m `"$trailer`"", 2, 'call operator and quoted executable'),
    @($attribution, 'PowerShell', "`"gh`" pr create -t t -b `"$trailer`"", 2, 'quoted gh executable'),
    @($attribution, 'PowerShell', "& 'C:\Program Files\Git\cmd\git.exe' commit -m `"$trailer`"", 2, 'full path to git.exe'),
    @($attribution, 'PowerShell', "Write-Output gh pr create -b `"$trailer`"", 0, 'gh only as an argument'),
    @($attribution, 'PowerShell', "Write-Output git commit -m `"$trailer`"", 0, 'git only as an argument'),
    @($attribution, 'PowerShell', "`$out = git commit -m `"$trailer`"", 2, 'assignment'),
    @($attribution, 'PowerShell', "Write-Output (git commit -m `"$trailer`")", 2, 'inside a subexpression'),
    @($attribution, 'Bash', "GIT_AUTHOR_NAME=x git commit -m `"$trailer`"", 2, 'Bash environment prefix'),
    @($attribution, 'PowerShell', 'git commit -Fmsg-bad.txt', 2, 'attached short -F value'),
    @($attribution, 'PowerShell', 'git commit --file=msg-bad.txt', 2, '--file= form'),
    @($attribution, 'PowerShell', 'git commit "-F" msg-bad.txt', 2, 'quoted option name'),

    @($issue, 'PowerShell', 'gh issue create --title "[DEBT] x" --body-file debt-ok.md', 0, 'DEBT complete'),
    @($issue, 'PowerShell', 'gh issue create --title "[DEBT] x" --body-file debt-missing.md', 2, 'DEBT missing Root Cause'),
    @($issue, 'PowerShell', 'gh issue create --title "[DEBT] x" --body-file debt-order.md', 2, 'DEBT out of order'),
    @($issue, 'PowerShell', 'gh issue create --title "[DEBT] x" --body-file free.md', 2, 'free-form body'),
    @($issue, 'PowerShell', 'gh issue create --title "[TECH-DEBT] x" --body-file debt-ok.md', 2, 'non-normalised prefix'),
    @($issue, 'PowerShell', 'gh issue create --title "No prefix" --body-file debt-ok.md', 2, 'no prefix'),
    @($issue, 'PowerShell', "gh issue create --title `"[DEBT] x`" --body `"$($debt -replace '"', '')`"", 0, 'inline body complete'),
    @($issue, 'PowerShell', "gh issue create --title '[DEBT] x' --body-file debt-ok.md", 0, 'single-quoted title'),
    @($issue, 'PowerShell', 'gh issue create --title $title --body-file $f', 0, 'variables'),
    @($issue, 'PowerShell', 'gh issue create --title "[DEBT] x" --body $body', 0, 'inline body from variable'),
    @($issue, 'PowerShell', 'gh issue create --title "[DEBT] x" --body (Get-Content b.md -Raw)', 0, 'inline body from subexpression'),
    @($issue, 'PowerShell', 'gh issue create --title "[DEBT] x" --body "$(cat b.md)"', 0, 'inline body from $()'),
    @($issue, 'PowerShell', 'gh issue create --repo stryker-mutator/stryker-net --title "Crash on xUnit v3" --body-file free.md', 0, 'other repository'),
    @($issue, 'PowerShell', 'gh issue create -R dlrivada/Encina --title "No prefix" --body-file debt-ok.md', 2, 'explicit Encina repository'),
    @($issue, 'PowerShell', "Select-String -Path x.md -Pattern 'gh issue create --title `"x`"'", 0, 'mentioned inside a string'),
    @($issue, 'PowerShell', 'git checkout -b fix/x; gh issue create --title "[DEBT] x" --template "Technical Debt"', 0, '--template after another statement'),
    @($issue, 'PowerShell', 'git commit -F msg-ok.txt && gh issue create --title "[DEBT] x" --body-file debt-ok.md', 0, '-F of an earlier git statement'),
    @($issue, 'PowerShell', 'gh issue create --title "[DEBT] x" --body "Free form. Repro: git commit -F msg.txt fails"', 2, '-F inside the body text'),
    @($issue, 'PowerShell', 'gh issue create --title "[DEBT] x" --body-file free-fenced.md', 2, 'headers only inside a fence'),
    @($issue, 'PowerShell', 'gh issue create --title "[DEBT] x" --body-file debt-quoted.md', 0, 'fenced header quoted in a valid body'),
    @($issue, 'PowerShell', 'gh issue create --title "[DEBT] x" --body-file debt-case.md', 2, 'header case differs'),
    @($issue, 'PowerShell', 'gh issue list --label bug', 0, 'not issue create'),
    @($issue, 'PowerShell', 'gh issue create "--title" "No prefix" --body-file debt-ok.md', 2, 'quoted --title'),
    @($issue, 'PowerShell', 'gh issue create --title="No prefix" --body-file debt-ok.md', 2, '--title= with quoted value'),
    @($issue, 'PowerShell', 'gh issue create -t"No prefix" -Fdebt-ok.md', 2, 'attached short options'),
    @($issue, 'PowerShell', 'gh issue create --title "[DEBT] x" -Ffree.md', 2, 'attached -F with a free-form body'),
    @($issue, 'PowerShell', 'gh issue create --title "[DEBT] x" --body "-F debt-ok.md"', 2, '-F as the body value'),
    @($issue, 'PowerShell', '& "gh" issue create --title "No prefix" --body-file debt-ok.md', 2, 'quoted gh with call operator'),
    @($issue, 'PowerShell', 'Write-Output gh issue create --title "No prefix" --body-file debt-ok.md', 0, 'gh only as an argument'),
    @($issue, 'PowerShell', '$r = (gh issue create --title "No prefix" --body-file debt-ok.md)', 2, 'assignment of a subexpression'),
    @($issue, 'PowerShell', "gh iss``ue create --title `"No prefix`" --body-file debt-ok.md", 2, 'backtick-escaped verb'),
    @($issue, 'PowerShell', 'gh issue create --title "[DEBT] x" --body-file debt-infostring.md', 0, 'backtick in fence info string is not a fence'),
    @($issue, 'PowerShell', 'not json', 0, 'malformed payload'),

    @($publish, 'PowerShell', 'git push', 2, 'git push'),
    @($publish, 'PowerShell', 'git -C dir push origin x', 2, 'git -C dir push'),
    @($publish, 'PowerShell', 'gh pr create --title t --body-file msg-ok.txt', 2, 'gh pr create'),
    @($publish, 'PowerShell', 'gh issue comment 5 -b x', 2, 'gh issue comment'),
    @($publish, 'PowerShell', 'gh api -X POST repos/o/r/issues', 2, 'gh api -X POST'),
    @($publish, 'PowerShell', 'git commit -m x', 0, 'git commit is allowed'),
    @($publish, 'PowerShell', 'gh pr view 5', 0, 'gh pr view is allowed'),
    @($publish, 'PowerShell', 'gh issue view 5', 0, 'gh issue view is allowed'),
    @($publish, 'PowerShell', 'gh api repos/o/r/pulls/5', 0, 'gh api GET is allowed'),
    @($publish, 'PowerShell', 'git log', 0, 'git log is allowed'),
    @($publish, 'PowerShell', 'git -c alias.publish=push publish', 2, 'git -c alias.publish=push publish'),
    @($publish, 'PowerShell', 'git config alias.p push', 2, 'git config alias.p push'),
    @($publish, 'PowerShell', 'git p', 2, 'git p (undefined alias, not on the allowlist)'),
    @($publish, 'PowerShell', 'git send-pack origin', 2, 'git send-pack'),
    @($publish, 'PowerShell', 'gh api repos/o/r/issues/5/comments -f body=x', 2, 'gh api -f defaults to POST'),
    @($publish, 'PowerShell', 'gh api repos/o/r/issues --input body.json', 2, 'gh api --input defaults to POST'),
    @($publish, 'PowerShell', 'git status', 0, 'git status is allowed'),
    @($publish, 'PowerShell', 'git worktree list', 0, 'git worktree list is allowed'),
    @($publish, 'PowerShell', 'git -C "dir x" log', 0, 'git -C quoted dir log is allowed'),
    @($publish, 'PowerShell', 'gh api -X GET repos/o/r/pulls -f state=open', 0, 'gh api explicit GET with fields is allowed'),
    @($publish, 'PowerShell', 'gh api repos/o/r/pulls/5', 0, 'gh api with no method or fields is allowed'),
    @($publish, 'PowerShell', 'git clone https://github.com/dlrivada/Encina.git C:\temp\x', 0, 'git clone is allowed'),
    @($publish, 'PowerShell', 'git -C D:\x clone ../repo target', 0, 'git -C dir clone is allowed')
)

# subagent_type, expected, label
$spawnCases = @(
    @('issue-worker', 2, 'issue-worker is blocked'),
    @('general-purpose', 2, 'general-purpose is blocked'),
    @($null, 2, 'missing subagent_type is blocked'),
    @('claude', 2, 'unknown subagent_type is blocked'),
    @('ci-diagnoser', 0, 'ci-diagnoser is allowed'),
    @('mechanical-fixer', 0, 'mechanical-fixer is allowed'),
    @('Explore', 0, 'Explore is allowed'),
    @('adversarial-reviewer', 0, 'adversarial-reviewer is allowed (self-review)'),
    @('docs-writer', 2, 'docs-writer is blocked'),
    @('Adversarial-Reviewer', 2, 'subagent_type is case-sensitive')
)

# block-main-checkout-writes.ps1 runs against a fake project: $main is the main checkout, $wt a worktree.
$main = Join-Path $work 'Encina'
$wt = Join-Path $main '.claude\worktrees\w1'
$outside = Join-Path $work 'outside'
function ConvertTo-Msys([string]$Path) { '/' + $Path.Substring(0, 1).ToLowerInvariant() + $Path.Substring(2).Replace('\', '/') }
$msysMain = ConvertTo-Msys $main
$msysWt = ConvertTo-Msys $wt

# tool, tool_input, cwd, expected, label[, CLAUDE_PROJECT_DIR (default $main)]
$writeCases = @(
    @('Write', @{ file_path = "$main\src\x.cs" }, $wt, 2, 'Write into the main checkout'),
    @('Write', @{ file_path = "$wt\src\x.cs" }, $main, 0, 'Write into a worktree'),
    @('Edit', @{ file_path = "$($main.Replace('\', '/'))/src/x.cs" }, $wt, 2, 'Edit with forward slashes into the main checkout'),
    @('Edit', @{ file_path = "$($main.ToUpperInvariant())\SRC\X.CS" }, $wt, 2, 'Edit into the main checkout with different case'),
    @('Edit', @{ file_path = "$($main.Replace('\', '/'))\src/x.cs" }, $wt, 2, 'Edit with mixed separators into the main checkout'),
    @('Write', @{ file_path = "$($wt.ToUpperInvariant())\x.md" }, $main, 0, 'Write into a worktree with different case'),
    @('Write', @{ file_path = "$($wt.Replace('\', '/'))/docs/x.md" }, $main, 0, 'Write into a worktree with forward slashes'),
    @('Write', @{ file_path = "$outside\x.md" }, $main, 0, 'Write outside the project (temp)'),
    @('NotebookEdit', @{ notebook_path = "$main\n.ipynb" }, $wt, 2, 'NotebookEdit into the main checkout'),
    @('Write', @{ file_path = "$wt\..\..\..\src\x.cs" }, $wt, 2, 'Write escaping the worktree with ..'),
    @('Write', @{ file_path = "$main\.claude\settings.json" }, $wt, 2, 'Write into the main .claude folder'),
    @('Write', @{ file_path = "$($main)2\x.cs" }, $wt, 0, 'sibling folder sharing the prefix'),
    @('Write', @{ file_path = 'src/x.cs' }, $main, 2, 'relative Write path from the main checkout'),
    @('Write', @{ file_path = "$main\src\x.cs" }, $wt, 2, 'project dir is a worktree, target in main', $wt),
    @('Write', @{ file_path = "$wt\src\x.cs" }, $wt, 0, 'project dir is a worktree, target in it', $wt),
    @('Read', @{ file_path = "$main\src\x.cs" }, $wt, 0, 'Read is not a write'),

    @('PowerShell', @{ command = "[IO.File]::WriteAllText('docs/x.txt', 'a')" }, $main, 2, 'relative [IO.File] write from the main checkout'),
    @('PowerShell', @{ command = "[System.IO.File]::AppendAllText(`"docs\x.txt`", 'a')" }, $main, 2, 'relative [System.IO.File] append from the main checkout'),
    @('PowerShell', @{ command = "[IO.File]::WriteAllText('docs/x.txt', 'a')" }, $wt, 0, 'relative [IO.File] write from a worktree'),
    @('PowerShell', @{ command = "Set-Location '$wt'; [IO.File]::WriteAllText('x.txt', 'a')" }, $main, 2, '[IO.File] ignores Set-Location'),
    @('PowerShell', @{ command = '[IO.File]::WriteAllText($path, $text)' }, $main, 0, '[IO.File] with a variable target'),
    @('PowerShell', @{ command = 'Set-Content -Path notes.txt -Value x' }, $main, 2, 'Set-Content relative in the main checkout'),
    @('PowerShell', @{ command = 'Set-Content -Path notes.txt -Value x' }, $wt, 0, 'Set-Content relative in a worktree'),
    @('PowerShell', @{ command = "Set-Content '$main\notes.txt' x" }, $wt, 2, 'Set-Content absolute into the main checkout'),
    @('PowerShell', @{ command = "Set-Location '$wt'; Set-Content notes.txt x" }, $main, 0, 'Set-Location into a worktree first'),
    @('PowerShell', @{ command = 'Set-Location $wt; Set-Content notes.txt x' }, $main, 0, 'Set-Location to a variable (unknown directory)'),
    @('PowerShell', @{ command = "'x' | Out-File out.txt" }, $main, 2, 'Out-File relative in the main checkout'),
    @('PowerShell', @{ command = 'Get-Content a.txt > b.txt' }, $main, 2, '> redirection in the main checkout'),
    @('PowerShell', @{ command = 'Get-Content a.txt >>b.txt' }, $main, 2, '>> attached redirection in the main checkout'),
    @('PowerShell', @{ command = "Get-Content a.txt > '$outside\b.txt'" }, $main, 0, 'redirection outside the project'),
    @('PowerShell', @{ command = 'git status 2>&1; Get-ChildItem > $null' }, $main, 0, '2>&1 and > $null are not writes'),
    @('PowerShell', @{ command = "Copy-Item '$outside\a.txt' docs\a.txt" }, $main, 2, 'Copy-Item into the main checkout'),
    @('PowerShell', @{ command = "Copy-Item docs\a.txt '$outside\a.txt'" }, $main, 0, 'Copy-Item out of the main checkout'),
    @('PowerShell', @{ command = "Move-Item -Path '$wt\a.txt' -Destination '$main\a.txt'" }, $wt, 2, 'Move-Item -Destination into the main checkout'),
    @('PowerShell', @{ command = 'New-Item -ItemType Directory scratch' }, $main, 2, 'New-Item relative in the main checkout'),
    @('PowerShell', @{ command = 'New-Item -ItemType Directory -Force $dir' }, $main, 0, 'New-Item with a variable target'),
    @('PowerShell', @{ command = 'git checkout -- src/x.cs' }, $main, 2, 'git checkout -- in the main checkout'),
    @('PowerShell', @{ command = 'git restore src/x.cs' }, $main, 2, 'git restore in the main checkout'),
    @('PowerShell', @{ command = 'git commit -m x' }, $main, 2, 'git commit in the main checkout'),
    @('PowerShell', @{ command = "git -C '$wt' restore src/x.cs" }, $main, 0, 'git -C worktree restore'),
    @('PowerShell', @{ command = "git -C '$wt' commit -m x" }, $main, 0, 'git -C worktree commit'),
    @('PowerShell', @{ command = "git -C '$main' commit -m x" }, $wt, 2, 'git -C main checkout commit'),
    @('PowerShell', @{ command = 'git status; git log --oneline -3; git diff; git stash list' }, $main, 0, 'read-only git in the main checkout'),
    @('PowerShell', @{ command = 'Get-Content src\x.cs; Get-ChildItem -Recurse src' }, $main, 0, 'read-only commands in the main checkout'),
    @('Bash', @{ command = 'echo x > notes.txt' }, $main, 2, 'Bash > in the main checkout'),
    @('Bash', @{ command = 'cp /c/tmp/a.txt notes.txt' }, $main, 2, 'Bash cp into the main checkout'),
    @('Bash', @{ command = "cd $msysWt && touch a.txt" }, $main, 0, 'Bash cd into a worktree (msys path) then touch'),
    @('Bash', @{ command = "touch $msysMain/a.txt" }, $wt, 2, 'Bash touch into the main checkout (msys path)'),
    @('PowerShell', @{ command = 'not json' }, $main, 0, 'malformed payload'),

    @('PowerShell', @{ command = "(Get-Content '$wt\src\x.cs') -replace 'a','b' | Set-Content '$wt\src\x.cs'" }, $wt, 2, '-replace piped to Set-Content on a .cs'),
    @('PowerShell', @{ command = "Set-Content -Path '$wt\docs\x.md' -Value y" }, $wt, 2, 'Set-Content on a .md in a worktree'),
    @('PowerShell', @{ command = "[IO.File]::WriteAllText('$wt\src\x.cs', `$c)" }, $wt, 2, '[IO.File] write to a .cs in a worktree'),
    @('PowerShell', @{ command = "'x' | Out-File '$wt\Directory.Build.props'" }, $wt, 2, 'Out-File on a .props'),
    @('PowerShell', @{ command = "Get-ChildItem '$wt\src' -Filter *.cs | ForEach-Object { (Get-Content `$_.FullName -Raw) -replace 'a','b' | Set-Content `$_.FullName }" }, $wt, 2, '-replace loop over *.cs with a variable target'),
    @('PowerShell', @{ command = "`$t = (Get-Content `$f -Raw).Replace('a', 'b'); [IO.File]::WriteAllText(`$f, `$t) # x.json" }, $wt, 2, '.Replace( with [IO.File] to a variable, .json named'),
    @('PowerShell', @{ command = "Set-Content '$wt\artifacts\issues\x.md' y" }, $wt, 0, 'artifacts are not repo files'),
    @('PowerShell', @{ command = "Set-Content '$outside\body.md' y" }, $wt, 0, 'source extension outside the project'),
    @('PowerShell', @{ command = "Set-Content '$wt\notes.txt' y" }, $wt, 0, 'non-source extension in a worktree'),
    @('PowerShell', @{ command = "`$c = 'x' -replace 'a','b'; Set-Content `$f `$c" }, $wt, 0, '-replace to a variable target, no source extension named'),
    @('PowerShell', @{ command = "dotnet format '$wt\Encina.slnx' --verify-no-changes" }, $wt, 0, 'dotnet format is not a text write'),
    @('Bash', @{ command = "echo x >> $msysWt/src/x.cs" }, $wt, 2, 'Bash >> to a .cs')
)

$failed = 0
Push-Location $work
try {
    foreach ($case in $cases) {
        $hook, $tool, $command, $expected, $label = $case
        $json = if ($command -eq 'not json') { 'not json' } else { @{ tool_name = $tool; cwd = $work; tool_input = @{ command = $command } } | ConvertTo-Json -Compress }
        $stderr = $json | pwsh -NoProfile -File $hook 2>&1
        $code = $LASTEXITCODE
        $ok = $code -eq $expected
        if (-not $ok) { $failed++ }
        "{0} [{1}, expected {2}] {3}: {4}" -f ($(if ($ok) { 'PASS' } else { 'FAIL' })), $code, $expected, (Split-Path -Leaf $hook), $label
        if (-not $ok -and $stderr) { "      $stderr" }
    }

    foreach ($case in $spawnCases) {
        $subagentType, $expected, $label = $case
        $toolInput = if ($null -eq $subagentType) { @{} } else { @{ subagent_type = $subagentType } }
        $json = @{ tool_name = 'Agent'; cwd = $work; tool_input = $toolInput } | ConvertTo-Json -Compress
        $stderr = $json | pwsh -NoProfile -File $spawn 2>&1
        $code = $LASTEXITCODE
        $ok = $code -eq $expected
        if (-not $ok) { $failed++ }
        "{0} [{1}, expected {2}] {3}: {4}" -f ($(if ($ok) { 'PASS' } else { 'FAIL' })), $code, $expected, (Split-Path -Leaf $spawn), $label
        if (-not $ok -and $stderr) { "      $stderr" }
    }

    foreach ($case in $writeCases) {
        $tool, $toolInput, $caseCwd, $expected, $label, $caseProject = $case
        $env:CLAUDE_PROJECT_DIR = if ($caseProject) { $caseProject } else { $main }
        $json = if ($toolInput.command -eq 'not json') { 'not json' } else { @{ tool_name = $tool; cwd = $caseCwd; tool_input = $toolInput } | ConvertTo-Json -Compress }
        $stderr = $json | pwsh -NoProfile -File $mainCheckout 2>&1
        $code = $LASTEXITCODE
        $ok = $code -eq $expected
        if (-not $ok) { $failed++ }
        "{0} [{1}, expected {2}] {3}: {4}" -f ($(if ($ok) { 'PASS' } else { 'FAIL' })), $code, $expected, (Split-Path -Leaf $mainCheckout), $label
        if (-not $ok -and $stderr) { "      $stderr" }
    }
    $env:CLAUDE_PROJECT_DIR = $repo

    $malformedStderr = 'not json' | pwsh -NoProfile -File $spawn 2>&1
    $malformedCode = $LASTEXITCODE
    $malformedOk = $malformedCode -eq 0
    if (-not $malformedOk) { $failed++ }
    "{0} [{1}, expected 0] {2}: {3}" -f ($(if ($malformedOk) { 'PASS' } else { 'FAIL' })), $malformedCode, (Split-Path -Leaf $spawn), 'malformed payload'
    if (-not $malformedOk -and $malformedStderr) { "      $malformedStderr" }
}
finally {
    Pop-Location
    Remove-Item -Recurse -Force $work
}

$totalCases = $cases.Count + $spawnCases.Count + $writeCases.Count + 1
"{0} cases, {1} failed" -f $totalCases, $failed
exit ([int]($failed -gt 0))
