using System.Globalization;
using System.Text;

namespace Encina.Modules.Isolation;

/// <summary>
/// Generates SQL Server permission scripts for module isolation.
/// </summary>
/// <remarks>
/// <para>
/// This generator creates T-SQL scripts for SQL Server that implement
/// database-level module isolation through schema separation and permissions.
/// </para>
/// <para>
/// Generated scripts are idempotent using patterns like:
/// <list type="bullet">
/// <item><description>IF NOT EXISTS checks before CREATE statements</description></item>
/// <item><description>DROP IF EXISTS before CREATE for recreatable objects</description></item>
/// <item><description>GRANT statements (which are inherently idempotent)</description></item>
/// </list>
/// </para>
/// <para>
/// Password placeholders use the format <c>{{ModuleName_Password}}</c> and must be
/// replaced with actual passwords before execution.
/// </para>
/// </remarks>
/// <example>
/// <code>
/// var generator = new SqlServerPermissionScriptGenerator();
/// var options = new ModuleIsolationOptions();
/// options.AddSharedSchemas("shared", "lookup");
/// options.AddModuleSchema(new ModuleSchemaOptions
/// {
///     ModuleName = "Orders",
///     SchemaName = "orders",
///     DatabaseUser = "orders_user"
/// });
///
/// var scripts = generator.GenerateAllScripts(options);
/// foreach (var script in scripts.OrderBy(s => s.Order))
/// {
///     Console.WriteLine($"-- {script.Name}");
///     Console.WriteLine(script.Content);
/// }
/// </code>
/// </example>
public sealed class SqlServerPermissionScriptGenerator : IModulePermissionScriptGenerator
{
    /// <inheritdoc />
    public string ProviderName => "SqlServer";

    /// <inheritdoc />
    public PermissionScript GenerateSchemaCreationScript(ModuleIsolationOptions options)
    {
        ArgumentNullException.ThrowIfNull(options);

        var sb = new StringBuilder();
        sb.AppendLine("-- SQL Server Schema Creation Script");
        sb.AppendLine("-- Generated by Encina Module Isolation");
        sb.AppendLine("-- This script is idempotent and can be run multiple times safely");
        sb.AppendLine();

        // Create shared schemas
        foreach (var schema in options.SharedSchemas.OrderBy(s => s, StringComparer.OrdinalIgnoreCase))
        {
            AppendSchemaCreation(sb, schema);
        }

        // Create module schemas
        foreach (var module in options.ModuleSchemas.OrderBy(m => m.ModuleName, StringComparer.OrdinalIgnoreCase))
        {
            AppendSchemaCreation(sb, module.SchemaName);
        }

        sb.AppendLine("PRINT 'Schema creation completed successfully.';");

        return PermissionScript.ForSchemaCreation(sb.ToString());
    }

    /// <inheritdoc />
    public PermissionScript GenerateUserCreationScript(ModuleIsolationOptions options)
    {
        ArgumentNullException.ThrowIfNull(options);

        var sb = new StringBuilder();
        sb.AppendLine("-- SQL Server User Creation Script");
        sb.AppendLine("-- Generated by Encina Module Isolation");
        sb.AppendLine("-- IMPORTANT: Replace {{ModuleName_Password}} placeholders with actual passwords before execution");
        sb.AppendLine("-- This script is idempotent and can be run multiple times safely");
        sb.AppendLine();

        var modulesWithUsers = options.ModuleSchemas
            .Where(m => !string.IsNullOrWhiteSpace(m.DatabaseUser))
            .OrderBy(m => m.ModuleName, StringComparer.OrdinalIgnoreCase)
            .ToList();

        if (modulesWithUsers.Count == 0)
        {
            sb.AppendLine("-- No module users configured");
            sb.AppendLine("PRINT 'No module users to create.';");
        }
        else
        {
            foreach (var module in modulesWithUsers)
            {
                AppendUserCreation(sb, module);
            }

            sb.AppendLine("PRINT 'User creation completed successfully.';");
        }

        return PermissionScript.ForUserCreation(sb.ToString());
    }

    /// <inheritdoc />
    public PermissionScript GenerateGrantPermissionsScript(ModuleIsolationOptions options)
    {
        ArgumentNullException.ThrowIfNull(options);

        var sb = new StringBuilder();
        sb.AppendLine("-- SQL Server Permission Grant Script");
        sb.AppendLine("-- Generated by Encina Module Isolation");
        sb.AppendLine("-- This script is idempotent and can be run multiple times safely");
        sb.AppendLine();

        var modulesWithUsers = options.ModuleSchemas
            .Where(m => !string.IsNullOrWhiteSpace(m.DatabaseUser))
            .OrderBy(m => m.ModuleName, StringComparer.OrdinalIgnoreCase)
            .ToList();

        if (modulesWithUsers.Count == 0)
        {
            sb.AppendLine("-- No module users configured");
            sb.AppendLine("PRINT 'No permissions to grant.';");
        }
        else
        {
            foreach (var module in modulesWithUsers)
            {
                AppendModulePermissions(sb, module, options.SharedSchemas);
            }

            sb.AppendLine("PRINT 'Permission grants completed successfully.';");
        }

        return PermissionScript.ForGrantPermissions(sb.ToString());
    }

    /// <inheritdoc />
    public PermissionScript GenerateRevokePermissionsScript(ModuleIsolationOptions options)
    {
        ArgumentNullException.ThrowIfNull(options);

        var sb = new StringBuilder();
        sb.AppendLine("-- SQL Server Permission Revoke Script");
        sb.AppendLine("-- Generated by Encina Module Isolation");
        sb.AppendLine("-- Use this script to clean up permissions before reconfiguring");
        sb.AppendLine("-- This script is idempotent and can be run multiple times safely");
        sb.AppendLine();

        var modulesWithUsers = options.ModuleSchemas
            .Where(m => !string.IsNullOrWhiteSpace(m.DatabaseUser))
            .OrderBy(m => m.ModuleName, StringComparer.OrdinalIgnoreCase)
            .ToList();

        if (modulesWithUsers.Count == 0)
        {
            sb.AppendLine("-- No module users configured");
            sb.AppendLine("PRINT 'No permissions to revoke.';");
        }
        else
        {
            foreach (var module in modulesWithUsers)
            {
                AppendRevokePermissions(sb, module, options.SharedSchemas);
            }

            sb.AppendLine("PRINT 'Permission revokes completed successfully.';");
        }

        return PermissionScript.ForRevokePermissions(sb.ToString());
    }

    /// <inheritdoc />
    public IEnumerable<PermissionScript> GenerateAllScripts(ModuleIsolationOptions options)
    {
        ArgumentNullException.ThrowIfNull(options);

        yield return GenerateSchemaCreationScript(options);
        yield return GenerateUserCreationScript(options);
        yield return GenerateGrantPermissionsScript(options);
    }

    /// <inheritdoc />
    public PermissionScript GenerateModulePermissionsScript(
        ModuleSchemaOptions moduleOptions,
        IEnumerable<string> sharedSchemas)
    {
        ArgumentNullException.ThrowIfNull(moduleOptions);
        ArgumentNullException.ThrowIfNull(sharedSchemas);

        var sb = new StringBuilder();
        sb.AppendLine(CultureInfo.InvariantCulture, $"-- SQL Server Permission Script for Module: {moduleOptions.ModuleName}");
        sb.AppendLine("-- Generated by Encina Module Isolation");
        sb.AppendLine();

        if (string.IsNullOrWhiteSpace(moduleOptions.DatabaseUser))
        {
            sb.AppendLine("-- No database user configured for this module");
            sb.AppendLine("PRINT 'No permissions to configure - no database user specified.';");
        }
        else
        {
            // Schema creation
            AppendSchemaCreation(sb, moduleOptions.SchemaName);

            // User creation
            AppendUserCreation(sb, moduleOptions);

            // Permissions
            var sharedSet = sharedSchemas.ToHashSet(StringComparer.OrdinalIgnoreCase);
            AppendModulePermissions(sb, moduleOptions, sharedSet);

            sb.AppendLine(CultureInfo.InvariantCulture, $"PRINT 'Module {moduleOptions.ModuleName} permissions configured successfully.';");
        }

        return PermissionScript.ForModule(moduleOptions.ModuleName, sb.ToString());
    }

    /// <summary>
    /// Appends schema creation statement.
    /// </summary>
    private static void AppendSchemaCreation(StringBuilder sb, string schemaName)
    {
        sb.AppendLine(CultureInfo.InvariantCulture, $"-- Create schema: {schemaName}");
        sb.AppendLine(CultureInfo.InvariantCulture, $"IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = N'{EscapeSqlString(schemaName)}')");
        sb.AppendLine("BEGIN");
        sb.AppendLine(CultureInfo.InvariantCulture, $"    EXEC('CREATE SCHEMA [{EscapeSqlIdentifier(schemaName)}]');");
        sb.AppendLine(CultureInfo.InvariantCulture, $"    PRINT 'Created schema: {schemaName}';");
        sb.AppendLine("END");
        sb.AppendLine("ELSE");
        sb.AppendLine("BEGIN");
        sb.AppendLine(CultureInfo.InvariantCulture, $"    PRINT 'Schema already exists: {schemaName}';");
        sb.AppendLine("END");
        sb.AppendLine("GO");
        sb.AppendLine();
    }

    /// <summary>
    /// Appends user and login creation statements.
    /// </summary>
    private static void AppendUserCreation(StringBuilder sb, ModuleSchemaOptions module)
    {
        var user = module.DatabaseUser!;
        var loginName = $"{user}_login";
        var passwordPlaceholder = $"{{{{{module.ModuleName}_Password}}}}";

        sb.AppendLine(CultureInfo.InvariantCulture, $"-- Create login and user for module: {module.ModuleName}");

        // Create login (server level)
        sb.AppendLine(CultureInfo.InvariantCulture, $"IF NOT EXISTS (SELECT 1 FROM sys.server_principals WHERE name = N'{EscapeSqlString(loginName)}')");
        sb.AppendLine("BEGIN");
        sb.AppendLine(CultureInfo.InvariantCulture, $"    CREATE LOGIN [{EscapeSqlIdentifier(loginName)}] WITH PASSWORD = N'{passwordPlaceholder}';");
        sb.AppendLine(CultureInfo.InvariantCulture, $"    PRINT 'Created login: {loginName}';");
        sb.AppendLine("END");
        sb.AppendLine("ELSE");
        sb.AppendLine("BEGIN");
        sb.AppendLine(CultureInfo.InvariantCulture, $"    PRINT 'Login already exists: {loginName}';");
        sb.AppendLine("END");
        sb.AppendLine("GO");
        sb.AppendLine();

        // Create user (database level)
        sb.AppendLine(CultureInfo.InvariantCulture, $"IF NOT EXISTS (SELECT 1 FROM sys.database_principals WHERE name = N'{EscapeSqlString(user)}')");
        sb.AppendLine("BEGIN");
        sb.AppendLine(CultureInfo.InvariantCulture, $"    CREATE USER [{EscapeSqlIdentifier(user)}] FOR LOGIN [{EscapeSqlIdentifier(loginName)}];");
        sb.AppendLine(CultureInfo.InvariantCulture, $"    PRINT 'Created user: {user}';");
        sb.AppendLine("END");
        sb.AppendLine("ELSE");
        sb.AppendLine("BEGIN");
        sb.AppendLine(CultureInfo.InvariantCulture, $"    PRINT 'User already exists: {user}';");
        sb.AppendLine("END");
        sb.AppendLine("GO");
        sb.AppendLine();
    }

    /// <summary>
    /// Appends permission grant statements for a module.
    /// </summary>
    private static void AppendModulePermissions(
        StringBuilder sb,
        ModuleSchemaOptions module,
        IReadOnlySet<string> sharedSchemas)
    {
        var user = module.DatabaseUser!;

        sb.AppendLine(CultureInfo.InvariantCulture, $"-- Grant permissions for module: {module.ModuleName}");
        sb.AppendLine();

        // Full access to own schema
        sb.AppendLine(CultureInfo.InvariantCulture, $"-- Full access to module schema: {module.SchemaName}");
        sb.AppendLine(CultureInfo.InvariantCulture, $"GRANT SELECT, INSERT, UPDATE, DELETE ON SCHEMA::[{EscapeSqlIdentifier(module.SchemaName)}] TO [{EscapeSqlIdentifier(user)}];");
        sb.AppendLine(CultureInfo.InvariantCulture, $"GRANT EXECUTE ON SCHEMA::[{EscapeSqlIdentifier(module.SchemaName)}] TO [{EscapeSqlIdentifier(user)}];");
        sb.AppendLine(CultureInfo.InvariantCulture, $"PRINT 'Granted full access on schema {module.SchemaName} to {user}';");
        sb.AppendLine();

        // SELECT-only access to shared schemas
        foreach (var sharedSchema in sharedSchemas.OrderBy(s => s, StringComparer.OrdinalIgnoreCase))
        {
            sb.AppendLine(CultureInfo.InvariantCulture, $"-- Read-only access to shared schema: {sharedSchema}");
            sb.AppendLine(CultureInfo.InvariantCulture, $"GRANT SELECT ON SCHEMA::[{EscapeSqlIdentifier(sharedSchema)}] TO [{EscapeSqlIdentifier(user)}];");
            sb.AppendLine(CultureInfo.InvariantCulture, $"PRINT 'Granted SELECT on schema {sharedSchema} to {user}';");
        }

        if (sharedSchemas.Count > 0)
        {
            sb.AppendLine();
        }

        // SELECT-only access to additional allowed schemas
        foreach (var additionalSchema in module.AdditionalAllowedSchemas.OrderBy(s => s, StringComparer.OrdinalIgnoreCase))
        {
            // Skip if already in shared schemas
            if (sharedSchemas.Contains(additionalSchema))
            {
                continue;
            }

            sb.AppendLine(CultureInfo.InvariantCulture, $"-- Read-only access to additional schema: {additionalSchema}");
            sb.AppendLine(CultureInfo.InvariantCulture, $"GRANT SELECT ON SCHEMA::[{EscapeSqlIdentifier(additionalSchema)}] TO [{EscapeSqlIdentifier(user)}];");
            sb.AppendLine(CultureInfo.InvariantCulture, $"PRINT 'Granted SELECT on schema {additionalSchema} to {user}';");
        }

        sb.AppendLine("GO");
        sb.AppendLine();
    }

    /// <summary>
    /// Appends permission revoke statements for a module.
    /// </summary>
    private static void AppendRevokePermissions(
        StringBuilder sb,
        ModuleSchemaOptions module,
        IReadOnlySet<string> sharedSchemas)
    {
        var user = module.DatabaseUser!;

        sb.AppendLine(CultureInfo.InvariantCulture, $"-- Revoke permissions for module: {module.ModuleName}");
        sb.AppendLine();

        // Revoke from own schema
        sb.AppendLine(CultureInfo.InvariantCulture, $"-- Revoke from module schema: {module.SchemaName}");
        sb.AppendLine(CultureInfo.InvariantCulture, $"REVOKE SELECT, INSERT, UPDATE, DELETE ON SCHEMA::[{EscapeSqlIdentifier(module.SchemaName)}] FROM [{EscapeSqlIdentifier(user)}];");
        sb.AppendLine(CultureInfo.InvariantCulture, $"REVOKE EXECUTE ON SCHEMA::[{EscapeSqlIdentifier(module.SchemaName)}] FROM [{EscapeSqlIdentifier(user)}];");
        sb.AppendLine(CultureInfo.InvariantCulture, $"PRINT 'Revoked permissions on schema {module.SchemaName} from {user}';");
        sb.AppendLine();

        // Revoke from shared schemas
        foreach (var sharedSchema in sharedSchemas.OrderBy(s => s, StringComparer.OrdinalIgnoreCase))
        {
            sb.AppendLine(CultureInfo.InvariantCulture, $"REVOKE SELECT ON SCHEMA::[{EscapeSqlIdentifier(sharedSchema)}] FROM [{EscapeSqlIdentifier(user)}];");
            sb.AppendLine(CultureInfo.InvariantCulture, $"PRINT 'Revoked SELECT on schema {sharedSchema} from {user}';");
        }

        // Revoke from additional allowed schemas
        foreach (var additionalSchema in module.AdditionalAllowedSchemas.OrderBy(s => s, StringComparer.OrdinalIgnoreCase))
        {
            if (sharedSchemas.Contains(additionalSchema))
            {
                continue;
            }

            sb.AppendLine(CultureInfo.InvariantCulture, $"REVOKE SELECT ON SCHEMA::[{EscapeSqlIdentifier(additionalSchema)}] FROM [{EscapeSqlIdentifier(user)}];");
            sb.AppendLine(CultureInfo.InvariantCulture, $"PRINT 'Revoked SELECT on schema {additionalSchema} from {user}';");
        }

        sb.AppendLine("GO");
        sb.AppendLine();
    }

    /// <summary>
    /// Escapes a string value for use in SQL statements.
    /// </summary>
    private static string EscapeSqlString(string value)
    {
        return value.Replace("'", "''", StringComparison.Ordinal);
    }

    /// <summary>
    /// Escapes an identifier for use in SQL statements (inside brackets).
    /// </summary>
    private static string EscapeSqlIdentifier(string value)
    {
        return value.Replace("]", "]]", StringComparison.Ordinal);
    }
}
