using Amazon.KeyManagementService;
using Amazon.KeyManagementService.Model;
using Encina.Security.Encryption.Abstractions;
using LanguageExt;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using static LanguageExt.Prelude;

namespace Encina.Messaging.Encryption.AwsKms;

/// <summary>
/// AWS KMS implementation of <see cref="IKeyProvider"/> using envelope encryption.
/// </summary>
/// <remarks>
/// <para>
/// Uses AWS KMS <c>GenerateDataKey</c> and <c>Decrypt</c> operations for envelope encryption:
/// data encryption keys (DEKs) are generated by KMS, and the encrypted DEK is stored with
/// the ciphertext. During decryption, only the encrypted DEK is sent to KMS.
/// </para>
/// <para>
/// Key rotation in AWS KMS is handled automatically when enabled on the KMS key.
/// The <see cref="RotateKeyAsync"/> method triggers on-demand rotation.
/// </para>
/// <para>
/// This class is thread-safe and suitable for singleton registration.
/// </para>
/// </remarks>
public sealed partial class AwsKmsKeyProvider : IKeyProvider
{
    private readonly IAmazonKeyManagementService _kmsClient;
    private readonly AwsKmsOptions _options;
    private readonly ILogger<AwsKmsKeyProvider> _logger;

    /// <summary>
    /// Initializes a new instance of the <see cref="AwsKmsKeyProvider"/> class.
    /// </summary>
    /// <param name="kmsClient">The AWS KMS client.</param>
    /// <param name="options">The AWS KMS configuration options.</param>
    /// <param name="logger">The logger instance.</param>
    public AwsKmsKeyProvider(
        IAmazonKeyManagementService kmsClient,
        IOptions<AwsKmsOptions> options,
        ILogger<AwsKmsKeyProvider> logger)
    {
        ArgumentNullException.ThrowIfNull(kmsClient);
        ArgumentNullException.ThrowIfNull(options);
        ArgumentNullException.ThrowIfNull(logger);

        _kmsClient = kmsClient;
        _options = options.Value;
        _logger = logger;
    }

    /// <inheritdoc />
    public async ValueTask<Either<EncinaError, byte[]>> GetKeyAsync(
        string keyId,
        CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(keyId);

        try
        {
            // Generate a data key encrypted under the KMS key
            var request = new GenerateDataKeyRequest
            {
                KeyId = keyId,
                KeySpec = DataKeySpec.AES_256
            };

            var response = await _kmsClient.GenerateDataKeyAsync(request, cancellationToken)
                .ConfigureAwait(false);

            Log.KeyRetrieved(_logger, keyId);
            return Right<EncinaError, byte[]>(response.Plaintext.ToArray());
        }
        catch (NotFoundException)
        {
            Log.KeyNotFound(_logger, keyId);
            return Left<EncinaError, byte[]>(
                MessageEncryptionErrors.KeyNotFound(keyId));
        }
        catch (DisabledException)
        {
            Log.KeyDisabled(_logger, keyId);
            return Left<EncinaError, byte[]>(
                MessageEncryptionErrors.ProviderUnavailable($"KMS key '{keyId}' is disabled."));
        }
        catch (InvalidKeyUsageException ex)
        {
            Log.ProviderError(_logger, keyId, ex.Message, ex);
            return Left<EncinaError, byte[]>(
                MessageEncryptionErrors.ProviderUnavailable(ex.Message, ex));
        }
        catch (AmazonKeyManagementServiceException ex)
        {
            Log.ProviderError(_logger, keyId, ex.Message, ex);
            return Left<EncinaError, byte[]>(
                MessageEncryptionErrors.ProviderUnavailable(ex.Message, ex));
        }
    }

    /// <inheritdoc />
    public ValueTask<Either<EncinaError, string>> GetCurrentKeyIdAsync(
        CancellationToken cancellationToken = default)
    {
        var keyId = _options.KeyId;
        if (string.IsNullOrWhiteSpace(keyId))
        {
            return ValueTask.FromResult<Either<EncinaError, string>>(
                Left<EncinaError, string>(
                    MessageEncryptionErrors.ProviderUnavailable("KeyId is not configured in AwsKmsOptions.")));
        }

        Log.CurrentKeyResolved(_logger, keyId);
        return ValueTask.FromResult<Either<EncinaError, string>>(Right<EncinaError, string>(keyId));
    }

    /// <inheritdoc />
    public async ValueTask<Either<EncinaError, string>> RotateKeyAsync(
        CancellationToken cancellationToken = default)
    {
        var keyId = _options.KeyId;
        if (string.IsNullOrWhiteSpace(keyId))
        {
            return Left<EncinaError, string>(
                MessageEncryptionErrors.ProviderUnavailable("KeyId is not configured in AwsKmsOptions."));
        }

        try
        {
            // Trigger on-demand rotation of the KMS key
            var request = new RotateKeyOnDemandRequest
            {
                KeyId = keyId
            };

            var response = await _kmsClient.RotateKeyOnDemandAsync(request, cancellationToken)
                .ConfigureAwait(false);

            Log.KeyRotated(_logger, keyId);
            return Right<EncinaError, string>(response.KeyId);
        }
        catch (AmazonKeyManagementServiceException ex)
        {
            Log.RotationFailed(_logger, keyId, ex.Message, ex);
            return Left<EncinaError, string>(
                MessageEncryptionErrors.ProviderUnavailable($"Key rotation failed: {ex.Message}", ex));
        }
    }

    private static partial class Log
    {
        [LoggerMessage(EventId = 2510, Level = LogLevel.Debug,
            Message = "Data key generated from AWS KMS key '{KeyId}'.")]
        public static partial void KeyRetrieved(ILogger logger, string keyId);

        [LoggerMessage(EventId = 2511, Level = LogLevel.Debug,
            Message = "KMS key '{KeyId}' not found in AWS KMS.")]
        public static partial void KeyNotFound(ILogger logger, string keyId);

        [LoggerMessage(EventId = 2512, Level = LogLevel.Debug,
            Message = "Current key resolved to '{KeyId}' from AWS KMS options.")]
        public static partial void CurrentKeyResolved(ILogger logger, string keyId);

        [LoggerMessage(EventId = 2513, Level = LogLevel.Information,
            Message = "Key '{KeyId}' rotated in AWS KMS.")]
        public static partial void KeyRotated(ILogger logger, string keyId);

        [LoggerMessage(EventId = 2514, Level = LogLevel.Warning,
            Message = "KMS key '{KeyId}' is disabled.")]
        public static partial void KeyDisabled(ILogger logger, string keyId);

        [LoggerMessage(EventId = 2515, Level = LogLevel.Warning,
            Message = "AWS KMS provider error for key '{KeyId}': {Reason}")]
        public static partial void ProviderError(ILogger logger, string keyId, string reason, Exception exception);

        [LoggerMessage(EventId = 2516, Level = LogLevel.Error,
            Message = "Key rotation failed for '{KeyId}' in AWS KMS: {Reason}")]
        public static partial void RotationFailed(ILogger logger, string keyId, string reason, Exception exception);
    }
}
