using Encina.Messaging.ScatterGather;
using LanguageExt;
using Shouldly;
using static LanguageExt.Prelude;

namespace Encina.Tests.ScatterGather;

public sealed class ScatterGatherBuilderTests
{
    [Fact]
    public void Create_WithName_ReturnsNewBuilder()
    {
        // Act
        var builder = ScatterGatherBuilder.Create<TestRequest, TestResponse>("TestOperation");

        // Assert
        builder.ShouldNotBeNull();
    }

    [Fact]
    public void Create_WithoutName_ReturnsBuilderWithAutoGeneratedName()
    {
        // Act
        var builder = ScatterGatherBuilder.Create<TestRequest, TestResponse>();

        // Assert
        builder.ShouldNotBeNull();
    }

    [Fact]
    public void Create_WithNullName_ThrowsArgumentException()
    {
        // Act & Assert
        Should.Throw<ArgumentException>(() => ScatterGatherBuilder.Create<TestRequest, TestResponse>(null!));
    }

    [Fact]
    public void Create_WithEmptyName_ThrowsArgumentException()
    {
        // Act & Assert
        Should.Throw<ArgumentException>(() => ScatterGatherBuilder.Create<TestRequest, TestResponse>(""));
    }

    [Fact]
    public void ScatterTo_WithName_ReturnsScatterBuilder()
    {
        // Arrange
        var builder = ScatterGatherBuilder.Create<TestRequest, TestResponse>("TestOperation");

        // Act
        var scatterBuilder = builder.ScatterTo("Handler1");

        // Assert
        scatterBuilder.ShouldNotBeNull();
    }

    [Fact]
    public void ScatterTo_WithNullName_ThrowsArgumentException()
    {
        // Arrange
        var builder = ScatterGatherBuilder.Create<TestRequest, TestResponse>("TestOperation");

        // Act & Assert
        Should.Throw<ArgumentException>(() => builder.ScatterTo((string)null!));
    }

    [Fact]
    public void ScatterTo_WithEmptyName_ThrowsArgumentException()
    {
        // Arrange
        var builder = ScatterGatherBuilder.Create<TestRequest, TestResponse>("TestOperation");

        // Act & Assert
        Should.Throw<ArgumentException>(() => builder.ScatterTo(""));
    }

    [Fact]
    public void ScatterTo_InlineHandler_AddsHandler()
    {
        // Arrange
        var builder = ScatterGatherBuilder.Create<TestRequest, TestResponse>("TestOperation");

        // Act
        var result = builder
            .ScatterTo((req, ct) => ValueTask.FromResult(Right<EncinaError, TestResponse>(new TestResponse(100))))
            .GatherAll()
            .TakeFirst()
            .Build();

        // Assert
        result.ScatterCount.ShouldBe(1);
    }

    [Fact]
    public void ScatterTo_NamedInlineHandler_AddsHandlerWithName()
    {
        // Arrange
        var builder = ScatterGatherBuilder.Create<TestRequest, TestResponse>("TestOperation");

        // Act
        var result = builder
            .ScatterTo("CustomHandler", (req, ct) => ValueTask.FromResult(Right<EncinaError, TestResponse>(new TestResponse(100))))
            .GatherAll()
            .TakeFirst()
            .Build();

        // Assert
        result.ScatterCount.ShouldBe(1);
        result.ScatterHandlers[0].Name.ShouldBe("CustomHandler");
    }

    [Fact]
    public void ScatterTo_WithNullHandler_ThrowsArgumentNullException()
    {
        // Arrange
        var builder = ScatterGatherBuilder.Create<TestRequest, TestResponse>("TestOperation");

        // Act & Assert
        Should.Throw<ArgumentNullException>(() =>
            builder.ScatterTo((Func<TestRequest, CancellationToken, ValueTask<Either<EncinaError, TestResponse>>>)null!));
    }

    [Fact]
    public void ScatterBuilder_Execute_ReturnsParentBuilder()
    {
        // Arrange
        var builder = ScatterGatherBuilder.Create<TestRequest, TestResponse>("TestOperation");
        var scatterBuilder = builder.ScatterTo("Handler1");

        // Act
        var parentBuilder = scatterBuilder.Execute((req, ct) =>
            ValueTask.FromResult(Right<EncinaError, TestResponse>(new TestResponse(100))));

        // Assert
        parentBuilder.ShouldBe(builder);
    }

    [Fact]
    public void ScatterBuilder_WithPriority_SetsPriority()
    {
        // Arrange & Act
        var definition = ScatterGatherBuilder.Create<TestRequest, TestResponse>("TestOperation")
            .ScatterTo("Handler1")
                .WithPriority(10)
                .Execute(req => Right<EncinaError, TestResponse>(new TestResponse(100)))
            .ScatterTo("Handler2")
                .WithPriority(1)
                .Execute(req => Right<EncinaError, TestResponse>(new TestResponse(200)))
            .GatherAll()
            .TakeFirst()
            .Build();

        // Assert - handlers should be sorted by priority
        definition.ScatterHandlers[0].Name.ShouldBe("Handler2"); // Priority 1 first
        definition.ScatterHandlers[1].Name.ShouldBe("Handler1"); // Priority 10 second
    }

    [Fact]
    public void GatherAll_ReturnsGatherBuilder()
    {
        // Arrange
        var builder = ScatterGatherBuilder.Create<TestRequest, TestResponse>("TestOperation")
            .ScatterTo(req => Right<EncinaError, TestResponse>(new TestResponse(100)));

        // Act
        var gatherBuilder = builder.GatherAll();

        // Assert
        gatherBuilder.ShouldNotBeNull();
    }

    [Fact]
    public void GatherFirst_SetsWaitForFirstStrategy()
    {
        // Arrange & Act
        var definition = ScatterGatherBuilder.Create<TestRequest, TestResponse>("TestOperation")
            .ScatterTo(req => Right<EncinaError, TestResponse>(new TestResponse(100)))
            .GatherFirst()
            .TakeFirst()
            .Build();

        // Assert
        definition.Strategy.ShouldBe(GatherStrategy.WaitForFirst);
    }

    [Fact]
    public void GatherQuorum_SetsQuorumStrategy()
    {
        // Arrange & Act
        var definition = ScatterGatherBuilder.Create<TestRequest, TestResponse>("TestOperation")
            .ScatterTo(req => Right<EncinaError, TestResponse>(new TestResponse(100)))
            .ScatterTo(req => Right<EncinaError, TestResponse>(new TestResponse(200)))
            .ScatterTo(req => Right<EncinaError, TestResponse>(new TestResponse(300)))
            .GatherQuorum(2)
            .TakeFirst()
            .Build();

        // Assert
        definition.Strategy.ShouldBe(GatherStrategy.WaitForQuorum);
        definition.QuorumCount.ShouldBe(2);
    }

    [Fact]
    public void GatherQuorum_WithZeroCount_ThrowsArgumentOutOfRangeException()
    {
        // Arrange
        var builder = ScatterGatherBuilder.Create<TestRequest, TestResponse>("TestOperation");

        // Act & Assert
        Should.Throw<ArgumentOutOfRangeException>(() => builder.GatherQuorum(0));
    }

    [Fact]
    public void GatherQuorum_WithNegativeCount_ThrowsArgumentOutOfRangeException()
    {
        // Arrange
        var builder = ScatterGatherBuilder.Create<TestRequest, TestResponse>("TestOperation");

        // Act & Assert
        Should.Throw<ArgumentOutOfRangeException>(() => builder.GatherQuorum(-1));
    }

    [Fact]
    public void WithTimeout_SetsTimeout()
    {
        // Arrange & Act
        var definition = ScatterGatherBuilder.Create<TestRequest, TestResponse>("TestOperation")
            .ScatterTo(req => Right<EncinaError, TestResponse>(new TestResponse(100)))
            .WithTimeout(TimeSpan.FromSeconds(10))
            .GatherAll()
            .TakeFirst()
            .Build();

        // Assert
        definition.Timeout.ShouldBe(TimeSpan.FromSeconds(10));
    }

    [Fact]
    public void WithTimeout_WithZero_ThrowsArgumentOutOfRangeException()
    {
        // Arrange
        var builder = ScatterGatherBuilder.Create<TestRequest, TestResponse>("TestOperation");

        // Act & Assert
        Should.Throw<ArgumentOutOfRangeException>(() => builder.WithTimeout(TimeSpan.Zero));
    }

    [Fact]
    public void WithTimeout_WithNegative_ThrowsArgumentOutOfRangeException()
    {
        // Arrange
        var builder = ScatterGatherBuilder.Create<TestRequest, TestResponse>("TestOperation");

        // Act & Assert
        Should.Throw<ArgumentOutOfRangeException>(() => builder.WithTimeout(TimeSpan.FromSeconds(-1)));
    }

    [Fact]
    public void ExecuteSequentially_SetsParallelToFalse()
    {
        // Arrange & Act
        var definition = ScatterGatherBuilder.Create<TestRequest, TestResponse>("TestOperation")
            .ScatterTo(req => Right<EncinaError, TestResponse>(new TestResponse(100)))
            .ExecuteSequentially()
            .GatherAll()
            .TakeFirst()
            .Build();

        // Assert
        definition.ExecuteInParallel.ShouldBeFalse();
    }

    [Fact]
    public void ExecuteInParallel_SetsParallelToTrue()
    {
        // Arrange & Act
        var definition = ScatterGatherBuilder.Create<TestRequest, TestResponse>("TestOperation")
            .ScatterTo(req => Right<EncinaError, TestResponse>(new TestResponse(100)))
            .ExecuteSequentially()
            .ExecuteInParallel()
            .GatherAll()
            .TakeFirst()
            .Build();

        // Assert
        definition.ExecuteInParallel.ShouldBeTrue();
    }

    [Fact]
    public void ExecuteInParallel_WithMaxDegree_SetsMaxDegreeOfParallelism()
    {
        // Arrange & Act
        var definition = ScatterGatherBuilder.Create<TestRequest, TestResponse>("TestOperation")
            .ScatterTo(req => Right<EncinaError, TestResponse>(new TestResponse(100)))
            .ExecuteInParallel(4)
            .GatherAll()
            .TakeFirst()
            .Build();

        // Assert
        definition.ExecuteInParallel.ShouldBeTrue();
        definition.MaxDegreeOfParallelism.ShouldBe(4);
    }

    [Fact]
    public void ExecuteInParallel_WithZeroMaxDegree_ThrowsArgumentOutOfRangeException()
    {
        // Arrange
        var builder = ScatterGatherBuilder.Create<TestRequest, TestResponse>("TestOperation");

        // Act & Assert
        Should.Throw<ArgumentOutOfRangeException>(() => builder.ExecuteInParallel(0));
    }

    [Fact]
    public void WithMetadata_AddsMetadata()
    {
        // Arrange & Act
        var definition = ScatterGatherBuilder.Create<TestRequest, TestResponse>("TestOperation")
            .ScatterTo(req => Right<EncinaError, TestResponse>(new TestResponse(100)))
            .WithMetadata("key1", "value1")
            .WithMetadata("key2", 42)
            .GatherAll()
            .TakeFirst()
            .Build();

        // Assert
        definition.Metadata.ShouldNotBeNull();
        definition.Metadata["key1"].ShouldBe("value1");
        definition.Metadata["key2"].ShouldBe(42);
    }

    [Fact]
    public void Build_WithNoScatterHandlers_ThrowsInvalidOperationException()
    {
        // Arrange
        var builder = ScatterGatherBuilder.Create<TestRequest, TestResponse>("TestOperation");

        // Act & Assert
        Should.Throw<InvalidOperationException>(() => builder.Build());
    }

    [Fact]
    public void Build_WithNoGatherHandler_ThrowsInvalidOperationException()
    {
        // Arrange
        var builder = ScatterGatherBuilder.Create<TestRequest, TestResponse>("TestOperation")
            .ScatterTo(req => Right<EncinaError, TestResponse>(new TestResponse(100)));

        // Act & Assert
        Should.Throw<InvalidOperationException>(() => builder.Build());
    }

    [Fact]
    public void Build_WithQuorumExceedingHandlerCount_ThrowsInvalidOperationException()
    {
        // Arrange
        var builder = ScatterGatherBuilder.Create<TestRequest, TestResponse>("TestOperation")
            .ScatterTo(req => Right<EncinaError, TestResponse>(new TestResponse(100)))
            .GatherQuorum(5)
            .TakeFirst();

        // Act & Assert
        Should.Throw<InvalidOperationException>(() => builder.Build());
    }

    [Fact]
    public void Build_WithValidConfiguration_ReturnsDefinition()
    {
        // Arrange & Act
        var definition = ScatterGatherBuilder.Create<TestRequest, TestResponse>("TestOperation")
            .ScatterTo("Handler1", req => Right<EncinaError, TestResponse>(new TestResponse(100)))
            .ScatterTo("Handler2", req => Right<EncinaError, TestResponse>(new TestResponse(200)))
            .GatherAll()
            .TakeFirst()
            .Build();

        // Assert
        definition.ShouldNotBeNull();
        definition.Name.ShouldBe("TestOperation");
        definition.ScatterCount.ShouldBe(2);
        definition.Strategy.ShouldBe(GatherStrategy.WaitForAll);
    }

    [Fact]
    public void GatherBuilder_Aggregate_SetsGatherHandler()
    {
        // Arrange & Act
        var definition = ScatterGatherBuilder.Create<TestRequest, TestResponse>("TestOperation")
            .ScatterTo(req => Right<EncinaError, TestResponse>(new TestResponse(100)))
            .GatherAll()
            .Aggregate((results, ct) => ValueTask.FromResult(Right<EncinaError, TestResponse>(new TestResponse(999))))
            .Build();

        // Assert
        definition.GatherHandler.ShouldNotBeNull();
    }

    [Fact]
    public void GatherBuilder_AggregateSuccessful_FiltersOnlySuccessfulResults()
    {
        // Arrange & Act
        var definition = ScatterGatherBuilder.Create<TestRequest, TestResponse>("TestOperation")
            .ScatterTo(req => Right<EncinaError, TestResponse>(new TestResponse(100)))
            .GatherAllAllowingPartialFailures()
            .AggregateSuccessful(results =>
            {
                var sum = results.Sum(r => r.Value);
                return Right<EncinaError, TestResponse>(new TestResponse(sum));
            })
            .Build();

        // Assert
        definition.Strategy.ShouldBe(GatherStrategy.WaitForAllAllowPartial);
    }

    [Fact]
    public void GatherBuilder_TakeMin_SelectsMinimumValue()
    {
        // Arrange & Act
        var definition = ScatterGatherBuilder.Create<TestRequest, TestResponse>("TestOperation")
            .ScatterTo(req => Right<EncinaError, TestResponse>(new TestResponse(100)))
            .GatherAll()
            .TakeMin(r => r.Value)
            .Build();

        // Assert
        definition.GatherHandler.ShouldNotBeNull();
    }

    [Fact]
    public void GatherBuilder_TakeMax_SelectsMaximumValue()
    {
        // Arrange & Act
        var definition = ScatterGatherBuilder.Create<TestRequest, TestResponse>("TestOperation")
            .ScatterTo(req => Right<EncinaError, TestResponse>(new TestResponse(100)))
            .GatherAll()
            .TakeMax(r => r.Value)
            .Build();

        // Assert
        definition.GatherHandler.ShouldNotBeNull();
    }

    public sealed record TestRequest(string Query);
    public sealed record TestResponse(decimal Value);
}
