using Encina.Compliance.AIAct.Model;

namespace Encina.Compliance.AIAct.Attributes;

/// <summary>
/// Marks a request type as subject to AI transparency obligations under
/// Articles 13 and 50 of the EU AI Act.
/// </summary>
/// <remarks>
/// <para>
/// Article 50 establishes transparency obligations for providers and deployers of certain
/// AI systems, regardless of whether they are classified as high-risk. These obligations
/// ensure that natural persons are informed when interacting with AI or exposed to
/// AI-generated content.
/// </para>
/// <para>
/// Article 13 adds further transparency requirements specific to high-risk AI systems,
/// including instructions for use and interpretability of outputs.
/// </para>
/// <para>
/// The <c>AIActCompliancePipelineBehavior</c> uses this attribute to verify that the
/// required disclosure text is being presented to the affected natural persons. The
/// <see cref="ObligationType"/> determines which specific obligation applies.
/// </para>
/// </remarks>
/// <example>
/// <code>
/// [AITransparency(
///     "This response was generated by an AI assistant.",
///     ObligationType = TransparencyObligationType.ChatbotInteraction)]
/// public sealed record GenerateChatResponseCommand(string UserMessage) : ICommand&lt;ChatResponse&gt;;
///
/// [AITransparency(
///     "This image was generated using AI.",
///     ObligationType = TransparencyObligationType.AIGeneratedContent)]
/// public sealed record GenerateImageCommand(string Prompt) : ICommand&lt;GeneratedImage&gt;;
/// </code>
/// </example>
[AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = true)]
public sealed class AITransparencyAttribute : Attribute
{
    /// <summary>
    /// Initialises a new instance of the <see cref="AITransparencyAttribute"/> class
    /// with the required disclosure text.
    /// </summary>
    /// <param name="disclosureText">
    /// The text that must be disclosed to natural persons when they interact with or
    /// are exposed to outputs from the AI system.
    /// </param>
    public AITransparencyAttribute(string disclosureText)
    {
        DisclosureText = disclosureText;
    }

    /// <summary>
    /// Gets the disclosure text that must be presented to natural persons.
    /// </summary>
    /// <remarks>
    /// Article 50(1) requires that natural persons are informed they are interacting
    /// with an AI system. The disclosure text should be clear, concise, and appropriate
    /// for the context of use.
    /// </remarks>
    public string DisclosureText { get; }

    /// <summary>
    /// Gets or sets the specific transparency obligation type that applies.
    /// </summary>
    /// <remarks>
    /// Defaults to <see cref="TransparencyObligationType.AIGeneratedContent"/>.
    /// Set this to the most specific obligation type for accurate compliance tracking.
    /// </remarks>
    public TransparencyObligationType ObligationType { get; set; } = TransparencyObligationType.AIGeneratedContent;
}
